//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IlrGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IlrGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Message xmlns=&quot;SFA/ILR/2016-17&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;Header&gt;
        ///    &lt;CollectionDetails&gt;
        ///      &lt;Collection&gt;ILR&lt;/Collection&gt;
        ///      &lt;Year&gt;1617&lt;/Year&gt;
        ///      &lt;FilePreparationDate&gt;2017-05-05&lt;/FilePreparationDate&gt;
        ///    &lt;/CollectionDetails&gt;
        ///    &lt;Source&gt;
        ///      &lt;ProtectiveMarking&gt;OFFICIAL-SENSITIVE-Personal&lt;/ProtectiveMarking&gt;
        ///      &lt;UKPRN&gt;10007459&lt;/UKPRN&gt;
        ///      &lt;SoftwareSupplier&gt;Software Supplier&lt;/SoftwareSupplier&gt;
        ///      &lt;SoftwarePackage&gt;Software Package&lt;/SoftwarePackage&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BaseIlr_1617 {
            get {
                return ResourceManager.GetString("BaseIlr_1617", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Message xmlns=&quot;SFA/ILR/2017-18&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;Header&gt;
        ///    &lt;CollectionDetails&gt;
        ///      &lt;Collection&gt;ILR&lt;/Collection&gt;
        ///      &lt;Year&gt;1718&lt;/Year&gt;
        ///      &lt;FilePreparationDate&gt;2017-05-05&lt;/FilePreparationDate&gt;
        ///    &lt;/CollectionDetails&gt;
        ///    &lt;Source&gt;
        ///      &lt;ProtectiveMarking&gt;OFFICIAL-SENSITIVE-Personal&lt;/ProtectiveMarking&gt;
        ///      &lt;UKPRN&gt;10007459&lt;/UKPRN&gt;
        ///      &lt;SoftwareSupplier&gt;Software Supplier&lt;/SoftwareSupplier&gt;
        ///      &lt;SoftwarePackage&gt;Software Package&lt;/SoftwarePackage&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BaseIlr_1718 {
            get {
                return ResourceManager.GetString("BaseIlr_1718", resourceCulture);
            }
        }
    }
}
