//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFA.DAS.Payments.Automation.Application.UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SFA.DAS.Payments.Automation.Application.UnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature: When Handling Gherkin With Account Balances
        ///
        ///Scenario: Multiple employers with indefinate levy
        ///    Given the employer 1 has a levy balance &gt; agreed price for all months
        ///    And the employer 2 has a levy balance &gt; agreed price for all months
        ///    
        ///Scenario: Single employer with indefinate levy
        ///    Given levy balance &gt; agreed price for all months
        ///    
        ///Scenario: Single employer with no levy
        ///    Given levy balance = 0 for all months
        ///    
        ///Scenario: Multiple employers with specific levy per pe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WhenHandlingGherkinWithAccountBalances {
            get {
                return ResourceManager.GetString("WhenHandlingGherkinWithAccountBalances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature: When Handling Gherkin With Commitments
        ///
        ///Scenario: Multiple commitments for different employers
        ///	Given the following commitments exist on 03/12/2017:
        ///		| Employer   | commitment Id | version Id | ULN       | start date | end date   | agreed price | status    | effective from | effective to |
        ///		| employer 1 | 1             | 1          | learner a | 01/08/2017 | 31/08/2018 | 15000        | active    | 01/08/2017     | 31/10/2017   |
        ///		| employer 1 | 1             | 2          | learner a | 01/0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WhenHandlingGherkinWithCommitments {
            get {
                return ResourceManager.GetString("WhenHandlingGherkinWithCommitments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature: When Handling Gherkin With Contract Types
        ///
        ///Scenario: contract types
        ///When an ILR file is submitted on 03/12/2017 with the following data:
        ///    | ULN       | start date | planned end date | actual end date | completion status | Total training price | Total training price effective date | Total assessment price | Total assessment price effective date | Residual training price | Residual training price effective date | Residual assessment price | Residual assessment price effective date |
        ///    | lea [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WhenHandlingGherkinWithContractTypes {
            get {
                return ResourceManager.GetString("WhenHandlingGherkinWithContractTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario:1.
        /// </summary>
        internal static string WhenHandlingGherkinWithEmploymentStatuses {
            get {
                return ResourceManager.GetString("WhenHandlingGherkinWithEmploymentStatuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature: When Handling Gherkin With Submissions
        ///
        ///    Scenario: Standard ILR
        ///        When an ILR file is submitted with the following data:
        ///            | ULN       | start date | planned end date | actual end date | completion status | Total training price | Total training price effective date | Total assessment price | Total assessment price effective date |
        ///            | learner a | 04/08/2017 | 04/08/2018       |                 | continuing        | 12000                | 04/08/2017                  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WhenHandlingGherkinWithSubmissions {
            get {
                return ResourceManager.GetString("WhenHandlingGherkinWithSubmissions", resourceCulture);
            }
        }
    }
}
