-- =====================================================================================================
-- Generated by Data Dictionary
-- Date: 24 March 2017 13:07
-- Rulebase Versions:
--          ILR Apprenticeship Earnings Calc 1617, Version 1617.17
-- =====================================================================================================

	truncate table [Reference].[AEC_LatestInYearEarningHistory]
	insert into
		[Reference].[AEC_LatestInYearEarningHistory]
	select distinct
		[AEC_LatestInYearEarningHistory].[AppIdentifier],
		[AEC_LatestInYearEarningHistory].[AppProgCompletedInTheYearInput],
		[AEC_LatestInYearEarningHistory].[CollectionReturnCode],
		[AEC_LatestInYearEarningHistory].[CollectionYear],
		[AEC_LatestInYearEarningHistory].[DaysInYear],
		[AEC_LatestInYearEarningHistory].[FworkCode],
		[AEC_LatestInYearEarningHistory].[HistoricEffectiveTNPStartDateInput],
		[AEC_LatestInYearEarningHistory].[HistoricLearner1618StartInput],
		[AEC_LatestInYearEarningHistory].[HistoricTNP1Input],
		[AEC_LatestInYearEarningHistory].[HistoricTNP2Input],
		[AEC_LatestInYearEarningHistory].[HistoricTNP3Input],
		[AEC_LatestInYearEarningHistory].[HistoricTNP4Input],
		[AEC_LatestInYearEarningHistory].[HistoricTotal1618UpliftPaymentsInTheYearInput],
		[AEC_LatestInYearEarningHistory].[HistoricVirtualTNP3EndOfTheYearInput],
		[AEC_LatestInYearEarningHistory].[HistoricVirtualTNP4EndOfTheYearInput],
		[AEC_LatestInYearEarningHistory].[LearnRefNumber],
		[AEC_LatestInYearEarningHistory].[ProgrammeStartDateIgnorePathway],
		[AEC_LatestInYearEarningHistory].[ProgrammeStartDateMatchPathway],
		[AEC_LatestInYearEarningHistory].[ProgType],
		[AEC_LatestInYearEarningHistory].[PwayCode],
		[AEC_LatestInYearEarningHistory].[STDCode],
		[AEC_LatestInYearEarningHistory].[TotalProgAimPaymentsInTheYear],
		[AEC_LatestInYearEarningHistory].[UKPRN],
		[AEC_LatestInYearEarningHistory].[ULN],
		[AEC_LatestInYearEarningHistory].[UptoEndDate]
	from
		[Valid].[Learner]
		inner join [${AEC-History.servername}].[${AEC-History.databasename}].[${Schemaname}].[AEC_LatestInYearEarningHistory]
			on Learner.LearnRefNumber = AEC_LatestInYearEarningHistory.LearnRefNumber
			and Learner.ULN = AEC_LatestInYearEarningHistory.ULN
 
	truncate table [Reference].[LARS_ApprenticeshipFunding]
	insert into
		[Reference].[LARS_ApprenticeshipFunding]
	 select
		[LARS_ApprenticeshipFunding].[1618Incentive],
		[LARS_ApprenticeshipFunding].[ApprenticeshipCode],
		[LARS_ApprenticeshipFunding].[ApprenticeshipType],
		[LARS_ApprenticeshipFunding].[EffectiveFrom],
		[LARS_ApprenticeshipFunding].[EffectiveTo],
		[LARS_ApprenticeshipFunding].[FundingCategory],
		[LARS_ApprenticeshipFunding].[MaxEmployerLevyCap],
		[LARS_ApprenticeshipFunding].[ProgType],
		[LARS_ApprenticeshipFunding].[PwayCode],
		[LARS_ApprenticeshipFunding].[ReservedValue1],
		[LARS_ApprenticeshipFunding].[ReservedValue2]
	from
		[Valid].[LearningDelivery]
		inner join [${UoD.FullyQualified}].[${LARS.schemaname}].[LARS_ApprenticeshipFunding]
		on [LARS_ApprenticeshipFunding].[ApprenticeshipType]='STD'
		and [LARS_ApprenticeshipFunding].[ApprenticeshipCode]=[LearningDelivery].[StdCode]
		and [LARS_ApprenticeshipFunding].[ProgType]=[LearningDelivery].[ProgType]
		and [LARS_ApprenticeshipFunding].[PwayCode]=0
	union select
		[LARS_ApprenticeshipFunding].[1618Incentive],
		[LARS_ApprenticeshipFunding].[ApprenticeshipCode],
		[LARS_ApprenticeshipFunding].[ApprenticeshipType],
		[LARS_ApprenticeshipFunding].[EffectiveFrom],
		[LARS_ApprenticeshipFunding].[EffectiveTo],
		[LARS_ApprenticeshipFunding].[FundingCategory],
		[LARS_ApprenticeshipFunding].[MaxEmployerLevyCap],
		[LARS_ApprenticeshipFunding].[ProgType],
		[LARS_ApprenticeshipFunding].[PwayCode],
		[LARS_ApprenticeshipFunding].[ReservedValue1],
		[LARS_ApprenticeshipFunding].[ReservedValue2]
	from
		[Valid].[LearningDelivery]
		inner join [${UoD.FullyQualified}].[${LARS.schemaname}].[LARS_ApprenticeshipFunding]
		on [LARS_ApprenticeshipFunding].[ApprenticeshipType]='FWK'
		and [LARS_ApprenticeshipFunding].[ApprenticeshipCode]=[LearningDelivery].[FworkCode]
		and [LARS_ApprenticeshipFunding].[ProgType]=[LearningDelivery].[ProgType]
		and [LARS_ApprenticeshipFunding].[PwayCode]=[LearningDelivery].[PwayCode]
 
	truncate table [Reference].[LARS_Current_Version]
	insert into
		[Reference].[LARS_Current_Version]
	select distinct
		[LARS_Current_Version].[CurrentVersion]
	from
		[${UoD.FullyQualified}].[${LARS.schemaname}].[LARS_Current_Version]
 
	truncate table [Reference].[LARS_FrameworkCmnComp]
	insert into
		[Reference].[LARS_FrameworkCmnComp]
	select distinct
		[LARS_FrameworkCmnComp].[CommonComponent],
		[LARS_FrameworkCmnComp].[EffectiveFrom],
		[LARS_FrameworkCmnComp].[EffectiveTo],
		[LARS_FrameworkCmnComp].[FworkCode],
		[LARS_FrameworkCmnComp].[ProgType],
		[LARS_FrameworkCmnComp].[PwayCode]
	from
		[${UoD.FullyQualified}].[${LARS.schemaname}].[LARS_FrameworkCmnComp]
inner merge join 
	[${UoD.FullyQualified}].[${LARS.schemaname}].[LARS_LearningDelivery]
			on [LARS_FrameworkCmnComp].[CommonComponent]=[LARS_LearningDelivery].[FrameworkCommonComponent]
		inner join [Valid].[LearningDelivery]
			on[LARS_LearningDelivery].[LearnAimRef]=[LearningDelivery].[LearnAimRef]
			and[LARS_FrameworkCmnComp].[FworkCode]=[LearningDelivery].[FworkCode]
			and[LARS_FrameworkCmnComp].[ProgType]=[LearningDelivery].[ProgType]
			and[LARS_FrameworkCmnComp].[PwayCode]=[LearningDelivery].[PwayCode]
 
	truncate table [Reference].[LARS_Funding]
	insert into
		[Reference].[LARS_Funding]
	select distinct
		[LARS_Funding].[EffectiveFrom]
		[LARS_Funding].[EffectiveTo]
		[LARS_Funding].[FundingCategory]
		[LARS_Funding].[RateWeighted]
	from
		[Valid].[LearningDelivery]
		inner join [${UoD.FullyQualified}].[${LARS.schemaname}].[LARS_Funding]
			on LearningDelivery.LearnAimRef = LARS_Funding.LearnAimRef
 
	truncate table [Reference].[LARS_LearningDelivery]
	insert into
		[Reference].[LARS_LearningDelivery]
	select distinct
		[LARS_LearningDelivery].[FrameworkCommonComponent]
		[LARS_LearningDelivery].[LearnAimRef]
	from
		[Valid].[LearningDelivery]
		inner join [${UoD.FullyQualified}].[${LARS.schemaname}].[LARS_LearningDelivery]
			on [LARS_LearningDelivery].[LearnAimRef]=[LearningDelivery].[LearnAimRef]
 
	truncate table [Reference].[LARS_StandardCommonComponent]
	insert into
		[Reference].[LARS_StandardCommonComponent]
	select distinct
		[LARS_StandardCommonComponent].[CommonComponent]
		[LARS_StandardCommonComponent].[EffectiveFrom]
		[LARS_StandardCommonComponent].[EffectiveTo]
		[LARS_StandardCommonComponent].[StandardCode]
	from
		[Valid].[LearningDelivery]
		inner join [${UoD.FullyQualified}].[${LARS.schemaname}].[LARS_StandardCommonComponent]
			on [LARS_StandardCommonComponent].[StandardCode]=[LearningDelivery].[StdCode]
 
	truncate table [Reference].[SFA_PostcodeDisadvantage]
	insert into
		[Reference].[SFA_PostcodeDisadvantage]
	select distinct
		[SFA_PostcodeDisadvantage].[EffectiveFrom]
		[SFA_PostcodeDisadvantage].[EffectiveTo]
		[SFA_PostcodeDisadvantage].[Postcode]
		[SFA_PostcodeDisadvantage].[Uplift]
	from
		[Valid].[Learner]
		inner join [${PostcodeFactors.FullyQualified}].[${Schemaname}].[SFA_PostcodeDisadvantage]
			on [SFA_PostcodeDisadvantage].[Postcode]=[Learner].[HomePostcode]
