// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SFA.DAS.Payments.AcceptanceTests.Features
{
    using TechTalk.SpecFlow;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Provider adjustments (EAS) payments")]
    [NUnit.Framework.CategoryAttribute("EAS1718")]
    public partial class ProviderAdjustmentsEASPaymentsFeature
    {

        private TechTalk.SpecFlow.ITestRunner testRunner;

#line 1 "provider_adjustments.feature"
#line hidden

        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-GB"), "Provider adjustments (EAS) payments", null, ProgrammingLanguage.CSharp, new string[] {
                        "EAS1718"});
            testRunner.OnFeatureStart(featureInfo);
        }

        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }

        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }

        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }

        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }

        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }

        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("1a. Submission nothing claimed (blank vanilla submission)")]
        public virtual void _1A_SubmissionNothingClaimedBlankVanillaSubmission()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("1a. Submission nothing claimed (blank vanilla submission)", ((string[])(null)));
#line 58
            this.ScenarioSetup(scenarioInfo);
#line 60
            testRunner.Given("the EAS collection period is 08/17", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17"});
            table1.AddRow(new string[] {
                        "16-18 Levy Excess Learning Support",
                        "0"});
            table1.AddRow(new string[] {
                        "16-18 Levy Exceptional Learning Support",
                        "0"});
            table1.AddRow(new string[] {
                        "16-18 Levy Audit Adjustments",
                        "0"});
            table1.AddRow(new string[] {
                        "16-18 Levy Authorised Claims",
                        "0"});
            table1.AddRow(new string[] {
                        "16-18 Levy Authorised Claims",
                        "0"});
            table1.AddRow(new string[] {
                        "16-18 Non Levy Excess Learning Support",
                        "0"});
            table1.AddRow(new string[] {
                        "16-18 Non Levy Exceptional Learning Support",
                        "0"});
            table1.AddRow(new string[] {
                        "16-18 Non Levy Audit Adjustments",
                        "0"});
            table1.AddRow(new string[] {
                        "16-18 Non Levy Authorised Claims",
                        "0"});
            table1.AddRow(new string[] {
                        "Adult Levy Excess Learning Support",
                        "0"});
            table1.AddRow(new string[] {
                        "Adult Levy Exceptional Learning Support",
                        "0"});
            table1.AddRow(new string[] {
                        "Adult Levy Audit Adjustments",
                        "0"});
            table1.AddRow(new string[] {
                        "Adult Levy Authorised Claims",
                        "0"});
            table1.AddRow(new string[] {
                        "Adult Non Levy Excess Learning Support",
                        "0"});
            table1.AddRow(new string[] {
                        "Adult Non Levy Exceptional Learning Support",
                        "0"});
            table1.AddRow(new string[] {
                        "Adult Non Levy Audit Adjustments",
                        "0"});
            table1.AddRow(new string[] {
                        "Adult Non Levy Authorised Claims",
                        "0"});
#line 61
            testRunner.When("the following EAS form is submitted:", ((string)(null)), table1, "When ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17"});
            table2.AddRow(new string[] {
                        "16-18 Levy Excess Learning Support",
                        "0",
                        "0"});
            table2.AddRow(new string[] {
                        "16-18 Levy Exceptional Learning Support",
                        "0",
                        "0"});
            table2.AddRow(new string[] {
                        "16-18 Levy Audit Adjustments",
                        "0",
                        "0"});
            table2.AddRow(new string[] {
                        "16-18 Levy Authorised Claims",
                        "0",
                        "0"});
            table2.AddRow(new string[] {
                        "16-18 Levy Authorised Claims",
                        "0",
                        "0"});
            table2.AddRow(new string[] {
                        "16-18 Non Levy Excess Learning Support",
                        "0",
                        "0"});
            table2.AddRow(new string[] {
                        "16-18 Non Levy Exceptional Learning Support",
                        "0",
                        "0"});
            table2.AddRow(new string[] {
                        "16-18 Non Levy Audit Adjustments",
                        "0",
                        "0"});
            table2.AddRow(new string[] {
                        "16-18 Non Levy Authorised Claims",
                        "0",
                        "0"});
            table2.AddRow(new string[] {
                        "Adult Levy Excess Learning Support",
                        "0",
                        "0"});
            table2.AddRow(new string[] {
                        "Adult Levy Exceptional Learning Support",
                        "0",
                        "0"});
            table2.AddRow(new string[] {
                        "Adult Levy Audit Adjustments",
                        "0",
                        "0"});
            table2.AddRow(new string[] {
                        "Adult Levy Authorised Claims",
                        "0",
                        "0"});
            table2.AddRow(new string[] {
                        "Adult Non Levy Excess Learning Support",
                        "0",
                        "0"});
            table2.AddRow(new string[] {
                        "Adult Non Levy Exceptional Learning Support",
                        "0",
                        "0"});
            table2.AddRow(new string[] {
                        "Adult Non Levy Audit Adjustments",
                        "0",
                        "0"});
            table2.AddRow(new string[] {
                        "Adult Non Levy Authorised Claims",
                        "0",
                        "0"});
#line 81
            testRunner.Then("the EAS payments are:", ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("1b. Submission for all claim lines")]
        public virtual void _1B_SubmissionForAllClaimLines()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("1b. Submission for all claim lines", ((string[])(null)));
#line 102
            this.ScenarioSetup(scenarioInfo);
#line 104
            testRunner.Given("the EAS collection period is 08/17", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17"});
            table3.AddRow(new string[] {
                        "16-18 Levy Excess Learning Support",
                        "10.01"});
            table3.AddRow(new string[] {
                        "16-18 Levy Exceptional Learning Support",
                        "11.02"});
            table3.AddRow(new string[] {
                        "16-18 Levy Audit Adjustments",
                        "12.03"});
            table3.AddRow(new string[] {
                        "16-18 Levy Authorised Claims",
                        "13.04"});
            table3.AddRow(new string[] {
                        "16-18 Levy Authorised Claims",
                        "14.05"});
            table3.AddRow(new string[] {
                        "16-18 Non Levy Excess Learning Support",
                        "15.06"});
            table3.AddRow(new string[] {
                        "16-18 Non Levy Exceptional Learning Support",
                        "16.07"});
            table3.AddRow(new string[] {
                        "16-18 Non Levy Audit Adjustments",
                        "17.08"});
            table3.AddRow(new string[] {
                        "16-18 Non Levy Authorised Claims",
                        "18.09"});
            table3.AddRow(new string[] {
                        "Adult Levy Excess Learning Support",
                        "20.10"});
            table3.AddRow(new string[] {
                        "Adult Levy Exceptional Learning Support",
                        "21.11"});
            table3.AddRow(new string[] {
                        "Adult Levy Audit Adjustments",
                        "22.12"});
            table3.AddRow(new string[] {
                        "Adult Levy Authorised Claims",
                        "23.13"});
            table3.AddRow(new string[] {
                        "Adult Non Levy Excess Learning Support",
                        "24.14"});
            table3.AddRow(new string[] {
                        "Adult Non Levy Exceptional Learning Support",
                        "25.15"});
            table3.AddRow(new string[] {
                        "Adult Non Levy Audit Adjustments",
                        "26.16"});
            table3.AddRow(new string[] {
                        "Adult Non Levy Authorised Claims",
                        "27.17"});
#line 105
            testRunner.When("the following EAS form is submitted:", ((string)(null)), table3, "When ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17"});
            table4.AddRow(new string[] {
                        "16-18 Levy Excess Learning Support",
                        "0",
                        "10.01"});
            table4.AddRow(new string[] {
                        "16-18 Levy Exceptional Learning Support",
                        "0",
                        "11.02"});
            table4.AddRow(new string[] {
                        "16-18 Levy Audit Adjustments",
                        "0",
                        "12.03"});
            table4.AddRow(new string[] {
                        "16-18 Levy Authorised Claims",
                        "0",
                        "13.04"});
            table4.AddRow(new string[] {
                        "16-18 Levy Authorised Claims",
                        "0",
                        "14.05"});
            table4.AddRow(new string[] {
                        "16-18 Non Levy Excess Learning Support",
                        "0",
                        "15.06"});
            table4.AddRow(new string[] {
                        "16-18 Non Levy Exceptional Learning Support",
                        "0",
                        "16.07"});
            table4.AddRow(new string[] {
                        "16-18 Non Levy Audit Adjustments",
                        "0",
                        "17.08"});
            table4.AddRow(new string[] {
                        "16-18 Non Levy Authorised Claims",
                        "0",
                        "18.09"});
            table4.AddRow(new string[] {
                        "Adult Levy Excess Learning Support",
                        "0",
                        "20.10"});
            table4.AddRow(new string[] {
                        "Adult Levy Exceptional Learning Support",
                        "0",
                        "21.11"});
            table4.AddRow(new string[] {
                        "Adult Levy Audit Adjustments",
                        "0",
                        "22.12"});
            table4.AddRow(new string[] {
                        "Adult Levy Authorised Claims",
                        "0",
                        "23.13"});
            table4.AddRow(new string[] {
                        "Adult Non Levy Excess Learning Support",
                        "0",
                        "24.14"});
            table4.AddRow(new string[] {
                        "Adult Non Levy Exceptional Learning Support",
                        "0",
                        "25.15"});
            table4.AddRow(new string[] {
                        "Adult Non Levy Audit Adjustments",
                        "0",
                        "26.16"});
            table4.AddRow(new string[] {
                        "Adult Non Levy Authorised Claims",
                        "0",
                        "27.17"});
#line 125
            testRunner.Then("the EAS payments are:", ((string)(null)), table4, "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("1c. Submission for not all claim lines")]
        public virtual void _1C_SubmissionForNotAllClaimLines()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("1c. Submission for not all claim lines", ((string[])(null)));
#line 146
            this.ScenarioSetup(scenarioInfo);
#line 148
            testRunner.Given("the EAS collection period is 08/17", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17"});
            table5.AddRow(new string[] {
                        "16-18 Levy Excess Learning Support",
                        "10.01"});
            table5.AddRow(new string[] {
                        "16-18 Levy Exceptional Learning Support",
                        "0"});
            table5.AddRow(new string[] {
                        "16-18 Levy Audit Adjustments",
                        "12.03"});
            table5.AddRow(new string[] {
                        "16-18 Levy Authorised Claims",
                        "0"});
            table5.AddRow(new string[] {
                        "16-18 Levy Authorised Claims",
                        "14.05"});
            table5.AddRow(new string[] {
                        "16-18 Non Levy Excess Learning Support",
                        "0"});
            table5.AddRow(new string[] {
                        "16-18 Non Levy Exceptional Learning Support",
                        "16.07"});
            table5.AddRow(new string[] {
                        "16-18 Non Levy Audit Adjustments",
                        "0"});
            table5.AddRow(new string[] {
                        "16-18 Non Levy Authorised Claims",
                        "18.09"});
            table5.AddRow(new string[] {
                        "Adult Levy Excess Learning Support",
                        "0"});
            table5.AddRow(new string[] {
                        "Adult Levy Exceptional Learning Support",
                        "21.11"});
            table5.AddRow(new string[] {
                        "Adult Levy Audit Adjustments",
                        "0"});
            table5.AddRow(new string[] {
                        "Adult Levy Authorised Claims",
                        "23.13"});
            table5.AddRow(new string[] {
                        "Adult Non Levy Excess Learning Support",
                        "0"});
            table5.AddRow(new string[] {
                        "Adult Non Levy Exceptional Learning Support",
                        "25.15"});
            table5.AddRow(new string[] {
                        "Adult Non Levy Audit Adjustments",
                        "0"});
            table5.AddRow(new string[] {
                        "Adult Non Levy Authorised Claims",
                        "27.17"});
#line 149
            testRunner.When("the following EAS form is submitted:", ((string)(null)), table5, "When ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17"});
            table6.AddRow(new string[] {
                        "16-18 Levy Excess Learning Support",
                        "0",
                        "10.01"});
            table6.AddRow(new string[] {
                        "16-18 Levy Exceptional Learning Support",
                        "0",
                        "0"});
            table6.AddRow(new string[] {
                        "16-18 Levy Audit Adjustments",
                        "0",
                        "12.03"});
            table6.AddRow(new string[] {
                        "16-18 Levy Authorised Claims",
                        "0",
                        "0"});
            table6.AddRow(new string[] {
                        "16-18 Levy Authorised Claims",
                        "0",
                        "14.05"});
            table6.AddRow(new string[] {
                        "16-18 Non Levy Excess Learning Support",
                        "0",
                        "0"});
            table6.AddRow(new string[] {
                        "16-18 Non Levy Exceptional Learning Support",
                        "0",
                        "16.07"});
            table6.AddRow(new string[] {
                        "16-18 Non Levy Audit Adjustments",
                        "0",
                        "0"});
            table6.AddRow(new string[] {
                        "16-18 Non Levy Authorised Claims",
                        "0",
                        "18.09"});
            table6.AddRow(new string[] {
                        "Adult Levy Excess Learning Support",
                        "0",
                        "0"});
            table6.AddRow(new string[] {
                        "Adult Levy Exceptional Learning Support",
                        "0",
                        "21.11"});
            table6.AddRow(new string[] {
                        "Adult Levy Audit Adjustments",
                        "0",
                        "0"});
            table6.AddRow(new string[] {
                        "Adult Levy Authorised Claims",
                        "0",
                        "23.13"});
            table6.AddRow(new string[] {
                        "Adult Non Levy Excess Learning Support",
                        "0",
                        "0"});
            table6.AddRow(new string[] {
                        "Adult Non Levy Exceptional Learning Support",
                        "0",
                        "25.15"});
            table6.AddRow(new string[] {
                        "Adult Non Levy Audit Adjustments",
                        "0",
                        "0"});
            table6.AddRow(new string[] {
                        "Adult Non Levy Authorised Claims",
                        "0",
                        "27.17"});
#line 169
            testRunner.Then("the EAS payments are:", ((string)(null)), table6, "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("2a. Submission for all claim lines")]
        public virtual void _2A_SubmissionForAllClaimLines()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("2a. Submission for all claim lines", ((string[])(null)));
#line 198
            this.ScenarioSetup(scenarioInfo);
#line 200
            testRunner.Given("the EAS collection period is 09/17", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17"});
            table7.AddRow(new string[] {
                        "16-18 Levy Excess Learning Support",
                        "10.01",
                        "0"});
            table7.AddRow(new string[] {
                        "16-18 Levy Exceptional Learning Support",
                        "11.02",
                        "0"});
            table7.AddRow(new string[] {
                        "16-18 Levy Audit Adjustments",
                        "12.03",
                        "0"});
            table7.AddRow(new string[] {
                        "16-18 Levy Authorised Claims",
                        "13.04",
                        "0"});
            table7.AddRow(new string[] {
                        "16-18 Levy Authorised Claims",
                        "14.05",
                        "0"});
            table7.AddRow(new string[] {
                        "16-18 Non Levy Excess Learning Support",
                        "15.06",
                        "0"});
            table7.AddRow(new string[] {
                        "16-18 Non Levy Exceptional Learning Support",
                        "16.07",
                        "0"});
            table7.AddRow(new string[] {
                        "16-18 Non Levy Audit Adjustments",
                        "17.08",
                        "0"});
            table7.AddRow(new string[] {
                        "16-18 Non Levy Authorised Claims",
                        "18.09",
                        "0"});
            table7.AddRow(new string[] {
                        "Adult Levy Excess Learning Support",
                        "20.10",
                        "0"});
            table7.AddRow(new string[] {
                        "Adult Levy Exceptional Learning Support",
                        "21.11",
                        "0"});
            table7.AddRow(new string[] {
                        "Adult Levy Audit Adjustments",
                        "22.12",
                        "0"});
            table7.AddRow(new string[] {
                        "Adult Levy Authorised Claims",
                        "23.13",
                        "0"});
            table7.AddRow(new string[] {
                        "Adult Non Levy Excess Learning Support",
                        "24.14",
                        "0"});
            table7.AddRow(new string[] {
                        "Adult Non Levy Exceptional Learning Support",
                        "25.15",
                        "0"});
            table7.AddRow(new string[] {
                        "Adult Non Levy Audit Adjustments",
                        "26.16",
                        "0"});
            table7.AddRow(new string[] {
                        "Adult Non Levy Authorised Claims",
                        "27.17",
                        "0"});
#line 201
            testRunner.When("the following EAS form is submitted:", ((string)(null)), table7, "When ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17"});
            table8.AddRow(new string[] {
                        "16-18 Levy Excess Learning Support",
                        "0",
                        "0",
                        "10.01"});
            table8.AddRow(new string[] {
                        "16-18 Levy Exceptional Learning Support",
                        "0",
                        "0",
                        "11.02"});
            table8.AddRow(new string[] {
                        "16-18 Levy Audit Adjustments",
                        "0",
                        "0",
                        "12.03"});
            table8.AddRow(new string[] {
                        "16-18 Levy Authorised Claims",
                        "0",
                        "0",
                        "13.04"});
            table8.AddRow(new string[] {
                        "16-18 Levy Authorised Claims",
                        "0",
                        "0",
                        "14.05"});
            table8.AddRow(new string[] {
                        "16-18 Non Levy Excess Learning Support",
                        "0",
                        "0",
                        "15.06"});
            table8.AddRow(new string[] {
                        "16-18 Non Levy Exceptional Learning Support",
                        "0",
                        "0",
                        "16.07"});
            table8.AddRow(new string[] {
                        "16-18 Non Levy Audit Adjustments",
                        "0",
                        "0",
                        "17.08"});
            table8.AddRow(new string[] {
                        "16-18 Non Levy Authorised Claims",
                        "0",
                        "0",
                        "18.09"});
            table8.AddRow(new string[] {
                        "Adult Levy Excess Learning Support",
                        "0",
                        "0",
                        "20.10"});
            table8.AddRow(new string[] {
                        "Adult Levy Exceptional Learning Support",
                        "0",
                        "0",
                        "21.11"});
            table8.AddRow(new string[] {
                        "Adult Levy Audit Adjustments",
                        "0",
                        "0",
                        "22.12"});
            table8.AddRow(new string[] {
                        "Adult Levy Authorised Claims",
                        "0",
                        "0",
                        "23.13"});
            table8.AddRow(new string[] {
                        "Adult Non Levy Excess Learning Support",
                        "0",
                        "0",
                        "24.14"});
            table8.AddRow(new string[] {
                        "Adult Non Levy Exceptional Learning Support",
                        "0",
                        "0",
                        "25.15"});
            table8.AddRow(new string[] {
                        "Adult Non Levy Audit Adjustments",
                        "0",
                        "0",
                        "26.16"});
            table8.AddRow(new string[] {
                        "Adult Non Levy Authorised Claims",
                        "0",
                        "0",
                        "27.17"});
#line 221
            testRunner.Then("the EAS payments are:", ((string)(null)), table8, "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("2b. Submission for not all claim lines")]
        public virtual void _2B_SubmissionForNotAllClaimLines()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("2b. Submission for not all claim lines", ((string[])(null)));
#line 242
            this.ScenarioSetup(scenarioInfo);
#line 244
            testRunner.Given("the EAS collection period is 09/17", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17"});
            table9.AddRow(new string[] {
                        "16-18 Levy Excess Learning Support",
                        "10.01",
                        "0"});
            table9.AddRow(new string[] {
                        "16-18 Levy Exceptional Learning Support",
                        "0",
                        "0"});
            table9.AddRow(new string[] {
                        "16-18 Levy Audit Adjustments",
                        "12.03",
                        "0"});
            table9.AddRow(new string[] {
                        "16-18 Levy Authorised Claims",
                        "0",
                        "0"});
            table9.AddRow(new string[] {
                        "16-18 Levy Authorised Claims",
                        "14.05",
                        "0"});
            table9.AddRow(new string[] {
                        "16-18 Non Levy Excess Learning Support",
                        "0",
                        "0"});
            table9.AddRow(new string[] {
                        "16-18 Non Levy Exceptional Learning Support",
                        "16.07",
                        "0"});
            table9.AddRow(new string[] {
                        "16-18 Non Levy Audit Adjustments",
                        "0",
                        "0"});
            table9.AddRow(new string[] {
                        "16-18 Non Levy Authorised Claims",
                        "18.09",
                        "0"});
            table9.AddRow(new string[] {
                        "Adult Levy Excess Learning Support",
                        "0",
                        "0"});
            table9.AddRow(new string[] {
                        "Adult Levy Exceptional Learning Support",
                        "21.11",
                        "0"});
            table9.AddRow(new string[] {
                        "Adult Levy Audit Adjustments",
                        "0",
                        "0"});
            table9.AddRow(new string[] {
                        "Adult Levy Authorised Claims",
                        "23.13",
                        "0"});
            table9.AddRow(new string[] {
                        "Adult Non Levy Excess Learning Support",
                        "0",
                        "0"});
            table9.AddRow(new string[] {
                        "Adult Non Levy Exceptional Learning Support",
                        "25.15",
                        "0"});
            table9.AddRow(new string[] {
                        "Adult Non Levy Audit Adjustments",
                        "0",
                        "0"});
            table9.AddRow(new string[] {
                        "Adult Non Levy Authorised Claims",
                        "27.17",
                        "0"});
#line 245
            testRunner.When("the following EAS form is submitted:", ((string)(null)), table9, "When ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17"});
            table10.AddRow(new string[] {
                        "16-18 Levy Excess Learning Support",
                        "0",
                        "0",
                        "10.01"});
            table10.AddRow(new string[] {
                        "16-18 Levy Exceptional Learning Support",
                        "0",
                        "0",
                        "0"});
            table10.AddRow(new string[] {
                        "16-18 Levy Audit Adjustments",
                        "0",
                        "0",
                        "12.03"});
            table10.AddRow(new string[] {
                        "16-18 Levy Authorised Claims",
                        "0",
                        "0",
                        "0"});
            table10.AddRow(new string[] {
                        "16-18 Levy Authorised Claims",
                        "0",
                        "0",
                        "14.05"});
            table10.AddRow(new string[] {
                        "16-18 Non Levy Excess Learning Support",
                        "0",
                        "0",
                        "0"});
            table10.AddRow(new string[] {
                        "16-18 Non Levy Exceptional Learning Support",
                        "0",
                        "0",
                        "16.07"});
            table10.AddRow(new string[] {
                        "16-18 Non Levy Audit Adjustments",
                        "0",
                        "0",
                        "0"});
            table10.AddRow(new string[] {
                        "16-18 Non Levy Authorised Claims",
                        "0",
                        "0",
                        "18.09"});
            table10.AddRow(new string[] {
                        "Adult Levy Excess Learning Support",
                        "0",
                        "0",
                        "0"});
            table10.AddRow(new string[] {
                        "Adult Levy Exceptional Learning Support",
                        "0",
                        "0",
                        "21.11"});
            table10.AddRow(new string[] {
                        "Adult Levy Audit Adjustments",
                        "0",
                        "0",
                        "0"});
            table10.AddRow(new string[] {
                        "Adult Levy Authorised Claims",
                        "0",
                        "0",
                        "23.13"});
            table10.AddRow(new string[] {
                        "Adult Non Levy Excess Learning Support",
                        "0",
                        "0",
                        "0"});
            table10.AddRow(new string[] {
                        "Adult Non Levy Exceptional Learning Support",
                        "0",
                        "0",
                        "25.15"});
            table10.AddRow(new string[] {
                        "Adult Non Levy Audit Adjustments",
                        "0",
                        "0",
                        "0"});
            table10.AddRow(new string[] {
                        "Adult Non Levy Authorised Claims",
                        "0",
                        "0",
                        "27.17"});
#line 265
            testRunner.Then("the EAS payments are:", ((string)(null)), table10, "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("3a. Submission for all claim lines")]
        public virtual void _3A_SubmissionForAllClaimLines()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("3a. Submission for all claim lines", ((string[])(null)));
#line 291
            this.ScenarioSetup(scenarioInfo);
#line 293
            testRunner.Given("the EAS collection period is 09/17", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17"});
            table11.AddRow(new string[] {
                        "16-18 Levy Excess Learning Support",
                        "10.01",
                        "28.18"});
            table11.AddRow(new string[] {
                        "16-18 Levy Exceptional Learning Support",
                        "11.02",
                        "29.19"});
            table11.AddRow(new string[] {
                        "16-18 Levy Audit Adjustments",
                        "12.03",
                        "30.20"});
            table11.AddRow(new string[] {
                        "16-18 Levy Authorised Claims",
                        "13.04",
                        "31.21"});
            table11.AddRow(new string[] {
                        "16-18 Levy Authorised Claims",
                        "14.05",
                        "32.22"});
            table11.AddRow(new string[] {
                        "16-18 Non Levy Excess Learning Support",
                        "15.06",
                        "33.23"});
            table11.AddRow(new string[] {
                        "16-18 Non Levy Exceptional Learning Support",
                        "16.07",
                        "34.23"});
            table11.AddRow(new string[] {
                        "16-18 Non Levy Audit Adjustments",
                        "17.08",
                        "35.24"});
            table11.AddRow(new string[] {
                        "16-18 Non Levy Authorised Claims",
                        "18.09",
                        "36.25"});
            table11.AddRow(new string[] {
                        "Adult Levy Excess Learning Support",
                        "20.10",
                        "37.26"});
            table11.AddRow(new string[] {
                        "Adult Levy Exceptional Learning Support",
                        "21.11",
                        "38.27"});
            table11.AddRow(new string[] {
                        "Adult Levy Audit Adjustments",
                        "22.12",
                        "39.28"});
            table11.AddRow(new string[] {
                        "Adult Levy Authorised Claims",
                        "23.13",
                        "40.29"});
            table11.AddRow(new string[] {
                        "Adult Non Levy Excess Learning Support",
                        "24.14",
                        "41.30"});
            table11.AddRow(new string[] {
                        "Adult Non Levy Exceptional Learning Support",
                        "25.15",
                        "42.31"});
            table11.AddRow(new string[] {
                        "Adult Non Levy Audit Adjustments",
                        "26.16",
                        "43.32"});
            table11.AddRow(new string[] {
                        "Adult Non Levy Authorised Claims",
                        "27.17",
                        "44.33"});
#line 294
            testRunner.When("the following EAS form is submitted:", ((string)(null)), table11, "When ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17"});
            table12.AddRow(new string[] {
                        "16-18 Levy Excess Learning Support",
                        "0",
                        "0",
                        "38.19"});
            table12.AddRow(new string[] {
                        "16-18 Levy Exceptional Learning Support",
                        "0",
                        "0",
                        "40.21"});
            table12.AddRow(new string[] {
                        "16-18 Levy Audit Adjustments",
                        "0",
                        "0",
                        "42.23"});
            table12.AddRow(new string[] {
                        "16-18 Levy Authorised Claims",
                        "0",
                        "0",
                        "44.25"});
            table12.AddRow(new string[] {
                        "16-18 Levy Authorised Claims",
                        "0",
                        "0",
                        "46.27"});
            table12.AddRow(new string[] {
                        "16-18 Non Levy Excess Learning Support",
                        "0",
                        "0",
                        "48.29"});
            table12.AddRow(new string[] {
                        "16-18 Non Levy Exceptional Learning Support",
                        "0",
                        "0",
                        "50.3"});
            table12.AddRow(new string[] {
                        "16-18 Non Levy Audit Adjustments",
                        "0",
                        "0",
                        "52.32"});
            table12.AddRow(new string[] {
                        "16-18 Non Levy Authorised Claims",
                        "0",
                        "0",
                        "54.34"});
            table12.AddRow(new string[] {
                        "Adult Levy Excess Learning Support",
                        "0",
                        "0",
                        "57.36"});
            table12.AddRow(new string[] {
                        "Adult Levy Exceptional Learning Support",
                        "0",
                        "0",
                        "59.38"});
            table12.AddRow(new string[] {
                        "Adult Levy Audit Adjustments",
                        "0",
                        "0",
                        "61.40"});
            table12.AddRow(new string[] {
                        "Adult Levy Authorised Claims",
                        "0",
                        "0",
                        "63.42"});
            table12.AddRow(new string[] {
                        "Adult Non Levy Excess Learning Support",
                        "0",
                        "0",
                        "65.44"});
            table12.AddRow(new string[] {
                        "Adult Non Levy Exceptional Learning Support",
                        "0",
                        "0",
                        "67.46"});
            table12.AddRow(new string[] {
                        "Adult Non Levy Audit Adjustments",
                        "0",
                        "0",
                        "69.48"});
            table12.AddRow(new string[] {
                        "Adult Non Levy Authorised Claims",
                        "0",
                        "0",
                        "71.50"});
#line 314
            testRunner.Then("the EAS payments are:", ((string)(null)), table12, "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("3b.  Submission for mixture of claim lines (some entered some not)")]
        public virtual void _3B_SubmissionForMixtureOfClaimLinesSomeEnteredSomeNot()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("3b.  Submission for mixture of claim lines (some entered some not)", ((string[])(null)));
#line 335
            this.ScenarioSetup(scenarioInfo);
#line 337
            testRunner.Given("the EAS collection period is 09/17", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17"});
            table13.AddRow(new string[] {
                        "16-18 Levy Excess Learning Support",
                        "10.01",
                        "0"});
            table13.AddRow(new string[] {
                        "16-18 Levy Exceptional Learning Support",
                        "0",
                        "29.19"});
            table13.AddRow(new string[] {
                        "16-18 Levy Audit Adjustments",
                        "12.03",
                        "0"});
            table13.AddRow(new string[] {
                        "16-18 Levy Authorised Claims",
                        "0",
                        "31.21"});
            table13.AddRow(new string[] {
                        "16-18 Levy Authorised Claims",
                        "14.05",
                        "0"});
            table13.AddRow(new string[] {
                        "16-18 Non Levy Excess Learning Support",
                        "0",
                        "33.23"});
            table13.AddRow(new string[] {
                        "16-18 Non Levy Exceptional Learning Support",
                        "16.07",
                        "0"});
            table13.AddRow(new string[] {
                        "16-18 Non Levy Audit Adjustments",
                        "0",
                        "35.25"});
            table13.AddRow(new string[] {
                        "16-18 Non Levy Authorised Claims",
                        "18.09",
                        "0"});
            table13.AddRow(new string[] {
                        "Adult Levy Excess Learning Support",
                        "0",
                        "37.27"});
            table13.AddRow(new string[] {
                        "Adult Levy Exceptional Learning Support",
                        "21.11",
                        "0"});
            table13.AddRow(new string[] {
                        "Adult Levy Audit Adjustments",
                        "0",
                        "39.29"});
            table13.AddRow(new string[] {
                        "Adult Levy Authorised Claims",
                        "23.13",
                        "0"});
            table13.AddRow(new string[] {
                        "Adult Non Levy Excess Learning Support",
                        "0",
                        "41.31"});
            table13.AddRow(new string[] {
                        "Adult Non Levy Exceptional Learning Support",
                        "25.15",
                        "0"});
            table13.AddRow(new string[] {
                        "Adult Non Levy Audit Adjustments",
                        "0",
                        "43.33"});
            table13.AddRow(new string[] {
                        "Adult Non Levy Authorised Claims",
                        "27.17",
                        "0"});
#line 338
            testRunner.When("the following EAS form is submitted:", ((string)(null)), table13, "When ");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17"});
            table14.AddRow(new string[] {
                        "16-18 Levy Excess Learning Support",
                        "0",
                        "0",
                        "10.01"});
            table14.AddRow(new string[] {
                        "16-18 Levy Exceptional Learning Support",
                        "0",
                        "0",
                        "29.19"});
            table14.AddRow(new string[] {
                        "16-18 Levy Audit Adjustments",
                        "0",
                        "0",
                        "12.03"});
            table14.AddRow(new string[] {
                        "16-18 Levy Authorised Claims",
                        "0",
                        "0",
                        "31.21"});
            table14.AddRow(new string[] {
                        "16-18 Levy Authorised Claims",
                        "0",
                        "0",
                        "14.05"});
            table14.AddRow(new string[] {
                        "16-18 Non Levy Excess Learning Support",
                        "0",
                        "0",
                        "33.23"});
            table14.AddRow(new string[] {
                        "16-18 Non Levy Exceptional Learning Support",
                        "0",
                        "0",
                        "16.07"});
            table14.AddRow(new string[] {
                        "16-18 Non Levy Audit Adjustments",
                        "0",
                        "0",
                        "35.25"});
            table14.AddRow(new string[] {
                        "16-18 Non Levy Authorised Claims",
                        "0",
                        "0",
                        "18.09"});
            table14.AddRow(new string[] {
                        "Adult Levy Excess Learning Support",
                        "0",
                        "0",
                        "37.27"});
            table14.AddRow(new string[] {
                        "Adult Levy Exceptional Learning Support",
                        "0",
                        "0",
                        "21.11"});
            table14.AddRow(new string[] {
                        "Adult Levy Audit Adjustments",
                        "0",
                        "0",
                        "39.29"});
            table14.AddRow(new string[] {
                        "Adult Levy Authorised Claims",
                        "0",
                        "0",
                        "23.13"});
            table14.AddRow(new string[] {
                        "Adult Non Levy Excess Learning Support",
                        "0",
                        "0",
                        "41.31"});
            table14.AddRow(new string[] {
                        "Adult Non Levy Exceptional Learning Support",
                        "0",
                        "0",
                        "25.15"});
            table14.AddRow(new string[] {
                        "Adult Non Levy Audit Adjustments",
                        "0",
                        "0",
                        "43.33"});
            table14.AddRow(new string[] {
                        "Adult Non Levy Authorised Claims",
                        "0",
                        "0",
                        "27.17"});
#line 358
            testRunner.Then("the EAS payments are:", ((string)(null)), table14, "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("4a. Submission for all claim lines")]
        public virtual void _4A_SubmissionForAllClaimLines()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("4a. Submission for all claim lines", ((string[])(null)));
#line 383
            this.ScenarioSetup(scenarioInfo);
#line 385
            testRunner.Given("the EAS collection period is 10/17", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17"});
            table15.AddRow(new string[] {
                        "16-18 Levy Excess Learning Support",
                        "10.01",
                        "28.18"});
            table15.AddRow(new string[] {
                        "16-18 Levy Exceptional Learning Support",
                        "11.02",
                        "29.19"});
            table15.AddRow(new string[] {
                        "16-18 Levy Audit Adjustments",
                        "12.03",
                        "30.20"});
            table15.AddRow(new string[] {
                        "16-18 Levy Authorised Claims",
                        "13.04",
                        "31.21"});
            table15.AddRow(new string[] {
                        "16-18 Levy Authorised Claims",
                        "14.05",
                        "32.22"});
            table15.AddRow(new string[] {
                        "16-18 Non Levy Excess Learning Support",
                        "15.06",
                        "33.23"});
            table15.AddRow(new string[] {
                        "16-18 Non Levy Exceptional Learning Support",
                        "16.07",
                        "34.23"});
            table15.AddRow(new string[] {
                        "16-18 Non Levy Audit Adjustments",
                        "17.08",
                        "35.24"});
            table15.AddRow(new string[] {
                        "16-18 Non Levy Authorised Claims",
                        "18.09",
                        "36.25"});
            table15.AddRow(new string[] {
                        "Adult Levy Excess Learning Support",
                        "20.10",
                        "37.26"});
            table15.AddRow(new string[] {
                        "Adult Levy Exceptional Learning Support",
                        "21.11",
                        "38.27"});
            table15.AddRow(new string[] {
                        "Adult Levy Audit Adjustments",
                        "22.12",
                        "39.28"});
            table15.AddRow(new string[] {
                        "Adult Levy Authorised Claims",
                        "23.13",
                        "40.29"});
            table15.AddRow(new string[] {
                        "Adult Non Levy Excess Learning Support",
                        "24.14",
                        "41.30"});
            table15.AddRow(new string[] {
                        "Adult Non Levy Exceptional Learning Support",
                        "25.15",
                        "42.31"});
            table15.AddRow(new string[] {
                        "Adult Non Levy Audit Adjustments",
                        "26.16",
                        "43.32"});
            table15.AddRow(new string[] {
                        "Adult Non Levy Authorised Claims",
                        "27.17",
                        "44.33"});
#line 386
            testRunner.And("the following EAS form is submitted in 09/17:", ((string)(null)), table15, "And ");
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17"});
            table16.AddRow(new string[] {
                        "16-18 Levy Exceptional Learning Support",
                        "0.01",
                        "28.18",
                        "0"});
            table16.AddRow(new string[] {
                        "16-18 Levy Audit Adjustments",
                        "21.02",
                        "29.19",
                        "0"});
            table16.AddRow(new string[] {
                        "16-18 Levy Excess Learning Support",
                        "2.03",
                        "30.20",
                        "0"});
            table16.AddRow(new string[] {
                        "16-18 Levy Authorised Claims",
                        "3.04",
                        "31.21",
                        "0"});
            table16.AddRow(new string[] {
                        "16-18 Levy Authorised Claims",
                        "24.05",
                        "32.22",
                        "0"});
            table16.AddRow(new string[] {
                        "16-18 Non Levy Excess Learning Support",
                        "25.06",
                        "33.23",
                        "0"});
            table16.AddRow(new string[] {
                        "16-18 Non Levy Exceptional Learning Support",
                        "26.07",
                        "34.23",
                        "0"});
            table16.AddRow(new string[] {
                        "16-18 Non Levy Audit Adjustments",
                        "27.08",
                        "35.24",
                        "0"});
            table16.AddRow(new string[] {
                        "16-18 Non Levy Authorised Claims",
                        "18.09",
                        "46.25",
                        "0"});
            table16.AddRow(new string[] {
                        "Adult Levy Excess Learning Support",
                        "20.10",
                        "47.26",
                        "0"});
            table16.AddRow(new string[] {
                        "Adult Levy Exceptional Learning Support",
                        "21.11",
                        "48.27",
                        "0"});
            table16.AddRow(new string[] {
                        "Adult Levy Audit Adjustments",
                        "22.12",
                        "49.28",
                        "0"});
            table16.AddRow(new string[] {
                        "Adult Levy Authorised Claims",
                        "13.13",
                        "30.29",
                        "0"});
            table16.AddRow(new string[] {
                        "Adult Non Levy Excess Learning Support",
                        "14.14",
                        "31.30",
                        "0"});
            table16.AddRow(new string[] {
                        "Adult Non Levy Exceptional Learning Support",
                        "15.15",
                        "32.31",
                        "0"});
            table16.AddRow(new string[] {
                        "Adult Non Levy Audit Adjustments",
                        "16.16",
                        "33.32",
                        "0"});
            table16.AddRow(new string[] {
                        "Adult Non Levy Authorised Claims",
                        "17.17",
                        "34.33",
                        "0"});
#line 406
            testRunner.When("the following EAS form is submitted:", ((string)(null)), table16, "When ");
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17"});
            table17.AddRow(new string[] {
                        "16-18 Levy Excess Learning Support",
                        "0",
                        "0",
                        "38.19",
                        "-10"});
            table17.AddRow(new string[] {
                        "16-18 Levy Exceptional Learning Support",
                        "0",
                        "0",
                        "40.21",
                        "10"});
            table17.AddRow(new string[] {
                        "16-18 Levy Audit Adjustments",
                        "0",
                        "0",
                        "42.23",
                        "-10"});
            table17.AddRow(new string[] {
                        "16-18 Levy Authorised Claims",
                        "0",
                        "0",
                        "44.25",
                        "-10"});
            table17.AddRow(new string[] {
                        "16-18 Levy Authorised Claims",
                        "0",
                        "0",
                        "46.27",
                        "10"});
            table17.AddRow(new string[] {
                        "16-18 Non Levy Excess Learning Support",
                        "0",
                        "0",
                        "48.29",
                        "10"});
            table17.AddRow(new string[] {
                        "16-18 Non Levy Exceptional Learning Support",
                        "0",
                        "0",
                        "50.30",
                        "10"});
            table17.AddRow(new string[] {
                        "16-18 Non Levy Audit Adjustments",
                        "0",
                        "0",
                        "52.32",
                        "10"});
            table17.AddRow(new string[] {
                        "16-18 Non Levy Authorised Claims",
                        "0",
                        "0",
                        "54.34",
                        "10"});
            table17.AddRow(new string[] {
                        "Adult Levy Excess Learning Support",
                        "0",
                        "0",
                        "57.36",
                        "10"});
            table17.AddRow(new string[] {
                        "Adult Levy Exceptional Learning Support",
                        "0",
                        "0",
                        "59.38",
                        "10"});
            table17.AddRow(new string[] {
                        "Adult Levy Audit Adjustments",
                        "0",
                        "0",
                        "61.40",
                        "10"});
            table17.AddRow(new string[] {
                        "Adult Levy Authorised Claims",
                        "0",
                        "0",
                        "63.42",
                        "-20"});
            table17.AddRow(new string[] {
                        "Adult Non Levy Excess Learning Support",
                        "0",
                        "0",
                        "65.44",
                        "-20"});
            table17.AddRow(new string[] {
                        "Adult Non Levy Exceptional Learning Support",
                        "0",
                        "0",
                        "67.46",
                        "-20"});
            table17.AddRow(new string[] {
                        "Adult Non Levy Audit Adjustments",
                        "0",
                        "0",
                        "69.48",
                        "-20"});
            table17.AddRow(new string[] {
                        "Adult Non Levy Authorised Claims",
                        "0",
                        "0",
                        "71.50",
                        "-20"});
#line 426
            testRunner.Then("the EAS payments are:", ((string)(null)), table17, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
