// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SFA.DAS.Payments.AcceptanceTests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Provider earnings and payments where learner is made redundant during learning")]
    [NUnit.Framework.CategoryAttribute("Redundancy")]
    public partial class ProviderEarningsAndPaymentsWhereLearnerIsMadeRedundantDuringLearningFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "redundancy_payments.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-GB"), "Provider earnings and payments where learner is made redundant during learning", null, ProgrammingLanguage.CSharp, new string[] {
                        "Redundancy"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("806_AC1- DAS learner, is made redundant within the last 6 months of planned learn" +
            "ing - receives full government funding for the rest of the programme")]
        public virtual void _806_AC1_DASLearnerIsMadeRedundantWithinTheLast6MonthsOfPlannedLearning_ReceivesFullGovernmentFundingForTheRestOfTheProgramme()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("806_AC1- DAS learner, is made redundant within the last 6 months of planned learn" +
                    "ing - receives full government funding for the rest of the programme", ((string[])(null)));
#line 5
this.ScenarioSetup(scenarioInfo);
#line 7
        testRunner.Given("The learner is programme only DAS", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 8
        testRunner.And("the apprenticeship funding band maximum is 15000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 9
        testRunner.And("levy balance > agreed price for all months", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table706 = new TechTalk.SpecFlow.Table(new string[] {
                        "commitment Id",
                        "version Id",
                        "Employer",
                        "Provider",
                        "ULN",
                        "start date",
                        "end date",
                        "agreed price",
                        "status",
                        "effective from",
                        "effective to"});
            table706.AddRow(new string[] {
                        "1",
                        "1",
                        "employer 1",
                        "provider a",
                        "learner a",
                        "01/08/2017",
                        "01/08/2018",
                        "15000",
                        "Active",
                        "01/08/2017",
                        ""});
#line 12
        testRunner.And("the following commitments exist:", ((string)(null)), table706, "And ");
#line hidden
            TechTalk.SpecFlow.Table table707 = new TechTalk.SpecFlow.Table(new string[] {
                        "ULN",
                        "learner type",
                        "start date",
                        "planned end date",
                        "actual end date",
                        "completion status",
                        "Total training price",
                        "Total training price effective date",
                        "Total assessment price",
                        "Total assessment price effective date"});
            table707.AddRow(new string[] {
                        "learner a",
                        "programme only DAS",
                        "03/08/2017",
                        "20/08/2018",
                        "",
                        "continuing",
                        "12000",
                        "03/08/2017",
                        "3000",
                        "03/08/2017"});
#line 16
        testRunner.When("an ILR file is submitted with the following data:", ((string)(null)), table707, "When ");
#line hidden
            TechTalk.SpecFlow.Table table708 = new TechTalk.SpecFlow.Table(new string[] {
                        "contract type",
                        "date from",
                        "date to"});
            table708.AddRow(new string[] {
                        "DAS",
                        "03/08/2017",
                        "20/02/2018"});
            table708.AddRow(new string[] {
                        "Non-DAS",
                        "21/02/2018",
                        ""});
#line 20
        testRunner.And("the Contract type in the ILR is:", ((string)(null)), table708, "And ");
#line hidden
            TechTalk.SpecFlow.Table table709 = new TechTalk.SpecFlow.Table(new string[] {
                        "Employer",
                        "Employment Status",
                        "Employment Status Applies"});
            table709.AddRow(new string[] {
                        "employer 1",
                        "in paid employment",
                        "02/08/2017"});
            table709.AddRow(new string[] {
                        "",
                        "not in paid employment",
                        "21/02/2018"});
#line 26
        testRunner.And("the employment status in the ILR is:", ((string)(null)), table709, "And ");
#line hidden
            TechTalk.SpecFlow.Table table710 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "...",
                        "01/18",
                        "02/18",
                        "03/18",
                        "04/18",
                        "05/18"});
            table710.AddRow(new string[] {
                        "Provider Earned Total",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "1000"});
            table710.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "1000"});
            table710.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table710.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "1000"});
            table710.AddRow(new string[] {
                        "Refund taken by SFA",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table710.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table710.AddRow(new string[] {
                        "Refund due to employer",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table710.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "1000",
                        "0",
                        "0",
                        "0"});
            table710.AddRow(new string[] {
                        "Levy account credited",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table710.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0",
                        "0",
                        "0",
                        "0"});
            table710.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table710.AddRow(new string[] {
                        "SFA non-Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "1000",
                        "1000",
                        "1000",
                        "1000"});
#line 31
        testRunner.Then("the provider earnings and payments break down as follows:", ((string)(null)), table710, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("806_AC2- DAS learner, is made redundant outside of the last 6 months of planned l" +
            "earning - receives full government funding for the next 12 weeks only")]
        [NUnit.Framework.CategoryAttribute("Redundancy")]
        public virtual void _806_AC2_DASLearnerIsMadeRedundantOutsideOfTheLast6MonthsOfPlannedLearning_ReceivesFullGovernmentFundingForTheNext12WeeksOnly()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("806_AC2- DAS learner, is made redundant outside of the last 6 months of planned l" +
                    "earning - receives full government funding for the next 12 weeks only", new string[] {
                        "Redundancy"});
#line 47
this.ScenarioSetup(scenarioInfo);
#line 49
        testRunner.Given("The learner is programme only DAS", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 50
        testRunner.And("the apprenticeship funding band maximum is 15000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 51
        testRunner.And("levy balance > agreed price for all months", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table711 = new TechTalk.SpecFlow.Table(new string[] {
                        "commitment Id",
                        "version Id",
                        "Employer",
                        "Provider",
                        "ULN",
                        "start date",
                        "end date",
                        "agreed price",
                        "status",
                        "effective from",
                        "effective to"});
            table711.AddRow(new string[] {
                        "1",
                        "1",
                        "employer 1",
                        "provider a",
                        "learner a",
                        "01/08/2017",
                        "01/08/2018",
                        "15000",
                        "Active",
                        "01/08/2017",
                        ""});
#line 54
        testRunner.And("the following commitments exist:", ((string)(null)), table711, "And ");
#line hidden
            TechTalk.SpecFlow.Table table712 = new TechTalk.SpecFlow.Table(new string[] {
                        "ULN",
                        "learner type",
                        "start date",
                        "planned end date",
                        "actual end date",
                        "completion status",
                        "Total training price",
                        "Total training price effective date",
                        "Total assessment price",
                        "Total assessment price effective date"});
            table712.AddRow(new string[] {
                        "learner a",
                        "programme only DAS",
                        "03/08/2017",
                        "20/08/2018",
                        "",
                        "continuing",
                        "12000",
                        "03/08/2017",
                        "3000",
                        "03/08/2017"});
#line 58
        testRunner.When("an ILR file is submitted with the following data:", ((string)(null)), table712, "When ");
#line hidden
            TechTalk.SpecFlow.Table table713 = new TechTalk.SpecFlow.Table(new string[] {
                        "contract type",
                        "date from",
                        "date to"});
            table713.AddRow(new string[] {
                        "DAS",
                        "03/08/2017",
                        "19/02/2018"});
            table713.AddRow(new string[] {
                        "Non-DAS",
                        "20/02/2018",
                        ""});
#line 62
        testRunner.And("the Contract type in the ILR is:", ((string)(null)), table713, "And ");
#line hidden
            TechTalk.SpecFlow.Table table714 = new TechTalk.SpecFlow.Table(new string[] {
                        "Employer",
                        "Employment Status",
                        "Employment Status Applies"});
            table714.AddRow(new string[] {
                        "employer 1",
                        "in paid employment",
                        "02/08/2017"});
            table714.AddRow(new string[] {
                        "",
                        "not in paid employment",
                        "20/02/2018"});
#line 67
        testRunner.And("the employment status in the ILR is:", ((string)(null)), table714, "And ");
#line hidden
            TechTalk.SpecFlow.Table table715 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "...",
                        "01/18",
                        "02/18",
                        "03/18",
                        "04/18",
                        "05/18"});
            table715.AddRow(new string[] {
                        "Provider Earned Total",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "0"});
            table715.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "0"});
            table715.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table715.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "1000"});
            table715.AddRow(new string[] {
                        "Refund taken by SFA",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table715.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table715.AddRow(new string[] {
                        "Refund due to employer",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table715.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "1000",
                        "0",
                        "0",
                        "0"});
            table715.AddRow(new string[] {
                        "Levy account credited",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table715.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0",
                        "0",
                        "0",
                        "0"});
            table715.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table715.AddRow(new string[] {
                        "SFA non-Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "1000",
                        "1000",
                        "1000",
                        "0"});
#line 72
        testRunner.Then("the provider earnings and payments break down as follows:", ((string)(null)), table715, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("807_AC1- Non-DAS learner, is made redundant within the last 6 months of planned l" +
            "earning - receives full government funding for the rest of the programme")]
        [NUnit.Framework.CategoryAttribute("Redundancy")]
        public virtual void _807_AC1_Non_DASLearnerIsMadeRedundantWithinTheLast6MonthsOfPlannedLearning_ReceivesFullGovernmentFundingForTheRestOfTheProgramme()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("807_AC1- Non-DAS learner, is made redundant within the last 6 months of planned l" +
                    "earning - receives full government funding for the rest of the programme", new string[] {
                        "Redundancy"});
#line 88
this.ScenarioSetup(scenarioInfo);
#line 90
        testRunner.Given("the apprenticeship funding band maximum is 15000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table716 = new TechTalk.SpecFlow.Table(new string[] {
                        "ULN",
                        "learner type",
                        "start date",
                        "planned end date",
                        "actual end date",
                        "completion status",
                        "Total training price",
                        "Total training price effective date",
                        "Total assessment price",
                        "Total assessment price effective date"});
            table716.AddRow(new string[] {
                        "learner a",
                        "programme only non-DAS",
                        "03/08/2017",
                        "20/08/2018",
                        "",
                        "continuing",
                        "12000",
                        "03/08/2017",
                        "3000",
                        "03/08/2017"});
#line 95
        testRunner.When("an ILR file is submitted with the following data:", ((string)(null)), table716, "When ");
#line hidden
            TechTalk.SpecFlow.Table table717 = new TechTalk.SpecFlow.Table(new string[] {
                        "Employer",
                        "Employment Status",
                        "Employment Status Applies"});
            table717.AddRow(new string[] {
                        "employer 1",
                        "in paid employment",
                        "02/08/2017"});
            table717.AddRow(new string[] {
                        "",
                        "not in paid employment",
                        "21/02/2018"});
#line 99
        testRunner.And("the employment status in the ILR is:", ((string)(null)), table717, "And ");
#line hidden
            TechTalk.SpecFlow.Table table718 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "...",
                        "01/18",
                        "02/18",
                        "03/18",
                        "04/18",
                        "05/18"});
            table718.AddRow(new string[] {
                        "Provider Earned Total",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "1000"});
            table718.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "900",
                        "900",
                        "900",
                        "...",
                        "900",
                        "1000",
                        "1000",
                        "1000",
                        "1000"});
            table718.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "100",
                        "100",
                        "100",
                        "...",
                        "100",
                        "0",
                        "0",
                        "0",
                        "0"});
            table718.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "900",
                        "900",
                        "...",
                        "900",
                        "900",
                        "1000",
                        "1000",
                        "1000"});
            table718.AddRow(new string[] {
                        "Refund taken by SFA",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table718.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "100",
                        "100",
                        "...",
                        "100",
                        "100",
                        "0",
                        "0",
                        "0"});
            table718.AddRow(new string[] {
                        "Refund due to employer",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table718.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table718.AddRow(new string[] {
                        "Levy account credited",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table718.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table718.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table718.AddRow(new string[] {
                        "SFA non-Levy co-funding budget",
                        "900",
                        "900",
                        "900",
                        "...",
                        "900",
                        "1000",
                        "1000",
                        "1000",
                        "1000"});
#line 104
        testRunner.Then("the provider earnings and payments break down as follows:", ((string)(null)), table718, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("807_AC2- Non-DAS learner, is made redundant outside of the last 6 months of plann" +
            "ed learning - receives full government funding for the next 12 weeks only")]
        public virtual void _807_AC2_Non_DASLearnerIsMadeRedundantOutsideOfTheLast6MonthsOfPlannedLearning_ReceivesFullGovernmentFundingForTheNext12WeeksOnly()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("807_AC2- Non-DAS learner, is made redundant outside of the last 6 months of plann" +
                    "ed learning - receives full government funding for the next 12 weeks only", ((string[])(null)));
#line 121
this.ScenarioSetup(scenarioInfo);
#line 123
        testRunner.Given("the apprenticeship funding band maximum is 15000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table719 = new TechTalk.SpecFlow.Table(new string[] {
                        "ULN",
                        "learner type",
                        "start date",
                        "planned end date",
                        "actual end date",
                        "completion status",
                        "Total training price",
                        "Total training price effective date",
                        "Total assessment price",
                        "Total assessment price effective date"});
            table719.AddRow(new string[] {
                        "learner a",
                        "programme only non-DAS",
                        "03/08/2017",
                        "20/08/2018",
                        "",
                        "continuing",
                        "12000",
                        "03/08/2017",
                        "3000",
                        "03/08/2017"});
#line 126
        testRunner.When("an ILR file is submitted with the following data:", ((string)(null)), table719, "When ");
#line hidden
            TechTalk.SpecFlow.Table table720 = new TechTalk.SpecFlow.Table(new string[] {
                        "Employer",
                        "Employment Status",
                        "Employment Status Applies"});
            table720.AddRow(new string[] {
                        "employer 1",
                        "in paid employment",
                        "02/08/2017"});
            table720.AddRow(new string[] {
                        "",
                        "not in paid employment",
                        "19/02/2018"});
#line 130
        testRunner.And("the employment status in the ILR is:", ((string)(null)), table720, "And ");
#line hidden
            TechTalk.SpecFlow.Table table721 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "...",
                        "01/18",
                        "02/18",
                        "03/18",
                        "04/18",
                        "05/18"});
            table721.AddRow(new string[] {
                        "Provider Earned Total",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "0"});
            table721.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "900",
                        "900",
                        "900",
                        "...",
                        "900",
                        "1000",
                        "1000",
                        "1000",
                        "0"});
            table721.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "100",
                        "100",
                        "100",
                        "...",
                        "100",
                        "0",
                        "0",
                        "0",
                        "0"});
            table721.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "900",
                        "900",
                        "...",
                        "900",
                        "900",
                        "1000",
                        "1000",
                        "1000"});
            table721.AddRow(new string[] {
                        "Refund taken by SFA",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table721.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "100",
                        "100",
                        "...",
                        "100",
                        "100",
                        "0",
                        "0",
                        "0"});
            table721.AddRow(new string[] {
                        "Refund due to employer",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table721.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table721.AddRow(new string[] {
                        "Levy account credited",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table721.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table721.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table721.AddRow(new string[] {
                        "SFA non-Levy co-funding budget",
                        "900",
                        "900",
                        "900",
                        "...",
                        "900",
                        "1000",
                        "1000",
                        "1000",
                        "0"});
#line 135
        testRunner.Then("the provider earnings and payments break down as follows:", ((string)(null)), table721, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("808_AC1- DAS learner, is made redundant within the last 6 months of planned learn" +
            "ing - receives full government funding for the rest of the programme, a provider" +
            " incentive, but no employer incentive")]
        public virtual void _808_AC1_DASLearnerIsMadeRedundantWithinTheLast6MonthsOfPlannedLearning_ReceivesFullGovernmentFundingForTheRestOfTheProgrammeAProviderIncentiveButNoEmployerIncentive()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("808_AC1- DAS learner, is made redundant within the last 6 months of planned learn" +
                    "ing - receives full government funding for the rest of the programme, a provider" +
                    " incentive, but no employer incentive", ((string[])(null)));
#line 151
this.ScenarioSetup(scenarioInfo);
#line 153
     testRunner.Given("The learner is programme only DAS", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 154
        testRunner.And("the apprenticeship funding band maximum is 9000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 155
        testRunner.And("levy balance > agreed price for all months", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table722 = new TechTalk.SpecFlow.Table(new string[] {
                        "commitment Id",
                        "version Id",
                        "ULN",
                        "framework code",
                        "programme type",
                        "pathway code",
                        "start date",
                        "end date",
                        "agreed price",
                        "status",
                        "effective from",
                        "effective to"});
            table722.AddRow(new string[] {
                        "1",
                        "1",
                        "learner a",
                        "403",
                        "2",
                        "1",
                        "01/08/2017",
                        "01/08/2018",
                        "6125",
                        "Active",
                        "01/08/2017",
                        ""});
#line 157
     testRunner.And("the following commitments exist:", ((string)(null)), table722, "And ");
#line hidden
            TechTalk.SpecFlow.Table table723 = new TechTalk.SpecFlow.Table(new string[] {
                        "ULN",
                        "learner type",
                        "aim type",
                        "framework code",
                        "programme type",
                        "pathway code",
                        "agreed price",
                        "aim rate",
                        "start date",
                        "planned end date",
                        "actual end date",
                        "completion status"});
            table723.AddRow(new string[] {
                        "learner a",
                        "16-18 programme only DAS",
                        "programme",
                        "403",
                        "2",
                        "1",
                        "6125",
                        "",
                        "06/08/2017",
                        "20/10/2018",
                        "08/08/2018",
                        "completed"});
            table723.AddRow(new string[] {
                        "learner a",
                        "16-18 programme only DAS",
                        "maths or english",
                        "403",
                        "2",
                        "1",
                        "",
                        "471",
                        "06/08/2017",
                        "06/10/2018",
                        "06/10/2018",
                        "completed"});
#line 161
     testRunner.When("an ILR file is submitted with the following data:", ((string)(null)), table723, "When ");
#line hidden
            TechTalk.SpecFlow.Table table724 = new TechTalk.SpecFlow.Table(new string[] {
                        "contract type",
                        "date from",
                        "date to"});
            table724.AddRow(new string[] {
                        "DAS",
                        "06/08/2017",
                        "20/04/2018"});
            table724.AddRow(new string[] {
                        "Non-DAS",
                        "21/04/2018",
                        ""});
#line 166
        testRunner.And("the Contract type in the ILR is:", ((string)(null)), table724, "And ");
#line hidden
            TechTalk.SpecFlow.Table table725 = new TechTalk.SpecFlow.Table(new string[] {
                        "Employer",
                        "Employment Status",
                        "Employment Status Applies"});
            table725.AddRow(new string[] {
                        "employer 1",
                        "in paid employment",
                        "05/08/2017"});
            table725.AddRow(new string[] {
                        "",
                        "not in paid employment",
                        "21/04/2018"});
#line 171
        testRunner.And("the employment status in the ILR is:", ((string)(null)), table725, "And ");
#line hidden
            TechTalk.SpecFlow.Table table726 = new TechTalk.SpecFlow.Table(new string[] {
                        "Learning support code",
                        "date from",
                        "date to"});
            table726.AddRow(new string[] {
                        "1",
                        "06/08/2017",
                        "20/10/2018"});
#line 176
          testRunner.And("the learning support status of the ILR is:", ((string)(null)), table726, "And ");
#line hidden
            TechTalk.SpecFlow.Table table727 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "12/17",
                        "...",
                        "03/18",
                        "04/18",
                        "05/18",
                        "...",
                        "08/18",
                        "09/18",
                        "10/18",
                        "11/18"});
            table727.AddRow(new string[] {
                        "Provider Earned Total",
                        "636.50",
                        "636.50",
                        "636.50",
                        "1636.50",
                        "636.50",
                        "...",
                        "636.50",
                        "636.50",
                        "636.50",
                        "...",
                        "3174.36",
                        "183.64",
                        "0",
                        "0"});
            table727.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "636.50",
                        "636.50",
                        "636.50",
                        "1636.50",
                        "636.50",
                        "...",
                        "636.50",
                        "636.50",
                        "636.50",
                        "...",
                        "3174.36",
                        "183.64",
                        "0",
                        "0"});
            table727.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0"});
            table727.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "636.50",
                        "636.50",
                        "636.50",
                        "1636.50",
                        "...",
                        "636.50",
                        "636.50",
                        "636.50",
                        "...",
                        "636.50",
                        "3174.36",
                        "183.64",
                        "0"});
            table727.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0"});
            table727.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "350",
                        "350",
                        "350",
                        "350",
                        "...",
                        "350",
                        "350",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0"});
            table727.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "350",
                        "350",
                        "350",
                        "350",
                        "350",
                        "...",
                        "350",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0"});
            table727.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0"});
            table727.AddRow(new string[] {
                        "SFA non-Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "350",
                        "350",
                        "...",
                        "1925",
                        "0",
                        "0",
                        "0"});
            table727.AddRow(new string[] {
                        "SFA Levy additional payments budget",
                        "286.50",
                        "286.50",
                        "286.50",
                        "1286.50",
                        "286.50",
                        "...",
                        "286.50",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0"});
            table727.AddRow(new string[] {
                        "SFA non-Levy additional payments budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "286.50",
                        "286.50",
                        "...",
                        "1249.3571",
                        "183.64",
                        "0",
                        "0"});
#line 181
        testRunner.Then("the provider earnings and payments break down as follows:", ((string)(null)), table727, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table728 = new TechTalk.SpecFlow.Table(new string[] {
                        "Payment type",
                        "09/17",
                        "10/17",
                        "11/17",
                        "12/17",
                        "...",
                        "02/18",
                        "03/18",
                        "04/18",
                        "...",
                        "09/18",
                        "10/18",
                        "11/18"});
            table728.AddRow(new string[] {
                        "On-program",
                        "350",
                        "350",
                        "350",
                        "350",
                        "...",
                        "350",
                        "350",
                        "350",
                        "...",
                        "0",
                        "0",
                        "0"});
            table728.AddRow(new string[] {
                        "Completion",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "...",
                        "1225",
                        "0",
                        "0"});
            table728.AddRow(new string[] {
                        "Balancing",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "...",
                        "700",
                        "0",
                        "0"});
            table728.AddRow(new string[] {
                        "English and maths on programme",
                        "33.64",
                        "33.64",
                        "33.64",
                        "33.64",
                        "...",
                        "33.64",
                        "33.64",
                        "33.64",
                        "...",
                        "33.64",
                        "33.64",
                        "0"});
            table728.AddRow(new string[] {
                        "English and maths Balancing",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0"});
            table728.AddRow(new string[] {
                        "Employer 16-18 incentive",
                        "0",
                        "0",
                        "0",
                        "500",
                        "...",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0"});
            table728.AddRow(new string[] {
                        "Provider 16-18 incentive",
                        "0",
                        "0",
                        "0",
                        "500",
                        "...",
                        "0",
                        "0",
                        "0",
                        "...",
                        "500",
                        "0",
                        "0"});
            table728.AddRow(new string[] {
                        "Framework uplift on-program",
                        "102.86",
                        "102.86",
                        "102.86",
                        "102.86",
                        "...",
                        "102.86",
                        "102.86",
                        "102.86",
                        "...",
                        "0",
                        "0",
                        "0"});
            table728.AddRow(new string[] {
                        "Framework uplift completion",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "...",
                        "360",
                        "0",
                        "0"});
            table728.AddRow(new string[] {
                        "Framework uplift balancing",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "...",
                        "205.71429",
                        "0",
                        "0"});
            table728.AddRow(new string[] {
                        "Provider disadvantage uplift",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0"});
            table728.AddRow(new string[] {
                        "Provider learning support",
                        "150",
                        "150",
                        "150",
                        "150",
                        "...",
                        "150",
                        "150",
                        "150",
                        "...",
                        "150",
                        "150",
                        "0"});
#line 195
        testRunner.And("the transaction types for the payments are:", ((string)(null)), table728, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("808-AC2- DAS learner, is made redundant outside the last 6 months of planned lear" +
            "ning - receives full government funding for the next 12 weeks only")]
        public virtual void _808_AC2_DASLearnerIsMadeRedundantOutsideTheLast6MonthsOfPlannedLearning_ReceivesFullGovernmentFundingForTheNext12WeeksOnly()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("808-AC2- DAS learner, is made redundant outside the last 6 months of planned lear" +
                    "ning - receives full government funding for the next 12 weeks only", ((string[])(null)));
#line 211
this.ScenarioSetup(scenarioInfo);
#line 213
     testRunner.Given("The learner is programme only DAS", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 214
        testRunner.And("the apprenticeship funding band maximum is 9000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 215
        testRunner.And("levy balance > agreed price for all months", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table729 = new TechTalk.SpecFlow.Table(new string[] {
                        "commitment Id",
                        "version Id",
                        "ULN",
                        "framework code",
                        "programme type",
                        "pathway code",
                        "start date",
                        "end date",
                        "agreed price",
                        "status",
                        "effective from",
                        "effective to"});
            table729.AddRow(new string[] {
                        "1",
                        "1",
                        "learner a",
                        "403",
                        "2",
                        "1",
                        "01/08/2017",
                        "01/08/2018",
                        "6125",
                        "Active",
                        "01/08/2017",
                        ""});
#line 218
     testRunner.And("the following commitments exist:", ((string)(null)), table729, "And ");
#line hidden
            TechTalk.SpecFlow.Table table730 = new TechTalk.SpecFlow.Table(new string[] {
                        "ULN",
                        "learner type",
                        "aim type",
                        "framework code",
                        "programme type",
                        "pathway code",
                        "agreed price",
                        "aim rate",
                        "start date",
                        "planned end date",
                        "actual end date",
                        "completion status"});
            table730.AddRow(new string[] {
                        "learner a",
                        "16-18 programme only DAS",
                        "programme",
                        "403",
                        "2",
                        "1",
                        "6125",
                        "",
                        "06/08/2017",
                        "20/10/2018",
                        "08/08/2018",
                        "completed"});
            table730.AddRow(new string[] {
                        "learner a",
                        "16-18 programme only DAS",
                        "maths or english",
                        "403",
                        "2",
                        "1",
                        "",
                        "471",
                        "06/08/2017",
                        "06/10/2018",
                        "06/10/2018",
                        "completed"});
#line 222
     testRunner.When("an ILR file is submitted with the following data:", ((string)(null)), table730, "When ");
#line hidden
            TechTalk.SpecFlow.Table table731 = new TechTalk.SpecFlow.Table(new string[] {
                        "contract type",
                        "date from",
                        "date to"});
            table731.AddRow(new string[] {
                        "DAS",
                        "06/08/2017",
                        "19/04/2018"});
            table731.AddRow(new string[] {
                        "Non-DAS",
                        "20/04/2018",
                        ""});
#line 227
        testRunner.And("the Contract type in the ILR is:", ((string)(null)), table731, "And ");
#line hidden
            TechTalk.SpecFlow.Table table732 = new TechTalk.SpecFlow.Table(new string[] {
                        "Employer",
                        "Employment Status",
                        "Employment Status Applies"});
            table732.AddRow(new string[] {
                        "employer 1",
                        "in paid employment",
                        "05/08/2017"});
            table732.AddRow(new string[] {
                        "",
                        "not in paid employment",
                        "20/04/2018"});
#line 232
        testRunner.And("the employment status in the ILR is:", ((string)(null)), table732, "And ");
#line hidden
            TechTalk.SpecFlow.Table table733 = new TechTalk.SpecFlow.Table(new string[] {
                        "Learning support code",
                        "date from",
                        "date to"});
            table733.AddRow(new string[] {
                        "1",
                        "06/08/2017",
                        "20/10/2018"});
#line 237
          testRunner.And("the learning support status of the ILR is:", ((string)(null)), table733, "And ");
#line hidden
            TechTalk.SpecFlow.Table table734 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "12/17",
                        "...",
                        "03/18",
                        "04/18",
                        "05/18",
                        "06/18",
                        "07/18",
                        "08/18",
                        "09/18",
                        "10/18",
                        "11/18"});
            table734.AddRow(new string[] {
                        "Provider Earned Total",
                        "636.50",
                        "636.50",
                        "636.50",
                        "1636.50",
                        "636.50",
                        "...",
                        "636.50",
                        "636.50",
                        "636.50",
                        "636.50",
                        "183.64",
                        "183.64",
                        "183.64",
                        "0",
                        "0"});
            table734.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "636.50",
                        "636.50",
                        "636.50",
                        "1636.50",
                        "636.50",
                        "...",
                        "636.50",
                        "636.50",
                        "636.50",
                        "636.50",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table734.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table734.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "636.50",
                        "636.50",
                        "636.50",
                        "1636.50",
                        "...",
                        "636.50",
                        "636.50",
                        "636.50",
                        "636.50",
                        "636.50",
                        "183.64",
                        "183.64",
                        "183.64",
                        "0"});
            table734.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table734.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "350",
                        "350",
                        "350",
                        "350",
                        "...",
                        "350",
                        "350",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table734.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "350",
                        "350",
                        "350",
                        "350",
                        "350",
                        "...",
                        "350",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table734.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table734.AddRow(new string[] {
                        "SFA non-Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "350",
                        "350",
                        "350",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table734.AddRow(new string[] {
                        "SFA Levy additional payments budget",
                        "286.50",
                        "286.50",
                        "286.50",
                        "1286.50",
                        "286.50",
                        "...",
                        "286.50",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table734.AddRow(new string[] {
                        "SFA non-Levy additional payments budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "286.50",
                        "286.50",
                        "286.50",
                        "183.64",
                        "183.64",
                        "183.64",
                        "0",
                        "0"});
#line 242
     testRunner.Then("the provider earnings and payments break down as follows:", ((string)(null)), table734, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table735 = new TechTalk.SpecFlow.Table(new string[] {
                        "Payment type",
                        "09/17",
                        "10/17",
                        "11/17",
                        "12/17",
                        "...",
                        "02/18",
                        "03/18",
                        "04/18",
                        "05/18",
                        "06/18",
                        "07/18",
                        "08/18"});
            table735.AddRow(new string[] {
                        "On-program",
                        "350",
                        "350",
                        "350",
                        "350",
                        "...",
                        "350",
                        "350",
                        "350",
                        "350",
                        "350",
                        "350",
                        "0"});
            table735.AddRow(new string[] {
                        "Completion",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table735.AddRow(new string[] {
                        "Balancing",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table735.AddRow(new string[] {
                        "English and maths on programme",
                        "33.64",
                        "33.64",
                        "33.64",
                        "33.64",
                        "...",
                        "33.64",
                        "33.64",
                        "33.64",
                        "33.64",
                        "33.64",
                        "33.64",
                        "33.64"});
            table735.AddRow(new string[] {
                        "English and maths Balancing",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table735.AddRow(new string[] {
                        "Employer 16-18 incentive",
                        "0",
                        "0",
                        "0",
                        "500",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table735.AddRow(new string[] {
                        "Provider 16-18 incentive",
                        "0",
                        "0",
                        "0",
                        "500",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table735.AddRow(new string[] {
                        "Framework uplift on-program",
                        "102.86",
                        "102.86",
                        "102.86",
                        "102.86",
                        "...",
                        "102.86",
                        "102.86",
                        "102.86",
                        "102.86",
                        "102.86",
                        "102.86",
                        "0"});
            table735.AddRow(new string[] {
                        "Framework uplift completion",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table735.AddRow(new string[] {
                        "Framework uplift balancing",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table735.AddRow(new string[] {
                        "Provider disadvantage uplift",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table735.AddRow(new string[] {
                        "Provider learning support",
                        "150",
                        "150",
                        "150",
                        "150",
                        "...",
                        "150",
                        "150",
                        "150",
                        "150",
                        "150",
                        "150",
                        "150"});
#line 256
        testRunner.And("the transaction types for the payments are:", ((string)(null)), table735, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("814-AC1- DAS learner, is made redundant within the last 6 months of planned learn" +
            "ing and completes late - receives full government funding for the rest of the pr" +
            "ogramme")]
        public virtual void _814_AC1_DASLearnerIsMadeRedundantWithinTheLast6MonthsOfPlannedLearningAndCompletesLate_ReceivesFullGovernmentFundingForTheRestOfTheProgramme()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("814-AC1- DAS learner, is made redundant within the last 6 months of planned learn" +
                    "ing and completes late - receives full government funding for the rest of the pr" +
                    "ogramme", ((string[])(null)));
#line 272
this.ScenarioSetup(scenarioInfo);
#line 274
        testRunner.Given("The learner is programme only DAS", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 275
        testRunner.And("the apprenticeship funding band maximum is 15000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 276
        testRunner.And("levy balance > agreed price for all months", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table736 = new TechTalk.SpecFlow.Table(new string[] {
                        "commitment Id",
                        "version Id",
                        "Employer",
                        "Provider",
                        "ULN",
                        "start date",
                        "end date",
                        "agreed price",
                        "status",
                        "effective from",
                        "effective to"});
            table736.AddRow(new string[] {
                        "1",
                        "1",
                        "employer 1",
                        "provider a",
                        "learner a",
                        "01/08/2017",
                        "01/08/2018",
                        "15000",
                        "Active",
                        "01/08/2017",
                        ""});
#line 279
        testRunner.And("the following commitments exist:", ((string)(null)), table736, "And ");
#line hidden
            TechTalk.SpecFlow.Table table737 = new TechTalk.SpecFlow.Table(new string[] {
                        "ULN",
                        "learner type",
                        "start date",
                        "planned end date",
                        "actual end date",
                        "completion status",
                        "Total training price",
                        "Total training price effective date",
                        "Total assessment price",
                        "Total assessment price effective date"});
            table737.AddRow(new string[] {
                        "learner a",
                        "programme only DAS",
                        "03/08/2017",
                        "20/08/2018",
                        "20/09/2018",
                        "completed",
                        "12000",
                        "03/08/2017",
                        "3000",
                        "03/08/2017"});
#line 283
        testRunner.When("an ILR file is submitted with the following data:", ((string)(null)), table737, "When ");
#line hidden
            TechTalk.SpecFlow.Table table738 = new TechTalk.SpecFlow.Table(new string[] {
                        "contract type",
                        "date from",
                        "date to"});
            table738.AddRow(new string[] {
                        "DAS",
                        "03/08/2017",
                        "20/02/2018"});
            table738.AddRow(new string[] {
                        "Non-DAS",
                        "21/02/2018",
                        "20/09/2018"});
#line 287
        testRunner.And("the Contract type in the ILR is:", ((string)(null)), table738, "And ");
#line hidden
            TechTalk.SpecFlow.Table table739 = new TechTalk.SpecFlow.Table(new string[] {
                        "Employer",
                        "Employment Status",
                        "Employment Status Applies"});
            table739.AddRow(new string[] {
                        "employer 1",
                        "in paid employment",
                        "02/08/2017"});
            table739.AddRow(new string[] {
                        "",
                        "not in paid employment",
                        "21/02/2018"});
#line 293
        testRunner.And("the employment status in the ILR is:", ((string)(null)), table739, "And ");
#line hidden
            TechTalk.SpecFlow.Table table740 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "...",
                        "01/18",
                        "02/18",
                        "03/18",
                        "04/18",
                        "05/18",
                        "...",
                        "07/18",
                        "08/18",
                        "09/18",
                        "10/18"});
            table740.AddRow(new string[] {
                        "Provider Earned Total",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0",
                        "3000",
                        "0"});
            table740.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0",
                        "3000",
                        "0"});
            table740.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0"});
            table740.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "1000",
                        "0",
                        "3000"});
            table740.AddRow(new string[] {
                        "Refund taken by SFA",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0"});
            table740.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0"});
            table740.AddRow(new string[] {
                        "Refund due to employer",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0"});
            table740.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "1000",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0"});
            table740.AddRow(new string[] {
                        "Levy account credited",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0"});
            table740.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0"});
            table740.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0",
                        "0",
                        "0"});
            table740.AddRow(new string[] {
                        "SFA non-Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0",
                        "3000",
                        "0"});
#line 298
        testRunner.Then("the provider earnings and payments break down as follows:", ((string)(null)), table740, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
