// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SFA.DAS.Payments.AcceptanceTests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Provider earnings and payments where learner refund payments are due")]
    [NUnit.Framework.CategoryAttribute("Refunds")]
    public partial class ProviderEarningsAndPaymentsWhereLearnerRefundPaymentsAreDueFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "refunds.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-GB"), "Provider earnings and payments where learner refund payments are due", null, ProgrammingLanguage.CSharp, new string[] {
                        "Refunds"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("673-AC01 DAS learner, levy available, provider retrospectively notifies a withdra" +
            "wal and previously-paid monthly instalments need to be refunded.")]
        public virtual void _673_AC01DASLearnerLevyAvailableProviderRetrospectivelyNotifiesAWithdrawalAndPreviously_PaidMonthlyInstalmentsNeedToBeRefunded_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("673-AC01 DAS learner, levy available, provider retrospectively notifies a withdra" +
                    "wal and previously-paid monthly instalments need to be refunded.", ((string[])(null)));
#line 4
this.ScenarioSetup(scenarioInfo);
#line 6
  testRunner.Given("The learner is programme only DAS", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 7
    testRunner.And("the apprenticeship funding band maximum is 17000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 8
    testRunner.And("levy balance > agreed price for all months", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table729 = new TechTalk.SpecFlow.Table(new string[] {
                        "commitment Id",
                        "version Id",
                        "ULN",
                        "start date",
                        "end date",
                        "status",
                        "agreed price",
                        "effective from",
                        "effective to"});
            table729.AddRow(new string[] {
                        "1",
                        "1",
                        "learner a",
                        "04/08/2017",
                        "01/08/2018",
                        "active",
                        "11250",
                        "01/08/2017",
                        ""});
#line 9
 testRunner.And("the following commitments exist:", ((string)(null)), table729, "And ");
#line hidden
            TechTalk.SpecFlow.Table table730 = new TechTalk.SpecFlow.Table(new string[] {
                        "ULN",
                        "start date",
                        "aim sequence number",
                        "completion status"});
            table730.AddRow(new string[] {
                        "learner a",
                        "04/08/2017",
                        "1",
                        "continuing"});
#line 13
 testRunner.And("following learning has been recorded for previous payments:", ((string)(null)), table730, "And ");
#line hidden
            TechTalk.SpecFlow.Table table731 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "12/17",
                        "01/18"});
            table731.AddRow(new string[] {
                        "Provider Earned Total",
                        "750",
                        "750",
                        "750",
                        "750",
                        "750",
                        "0"});
            table731.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "750",
                        "750",
                        "750",
                        "750",
                        "750",
                        "0"});
            table731.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table731.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "750",
                        "750",
                        "750",
                        "750",
                        "750"});
            table731.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table731.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "750",
                        "750",
                        "750",
                        "750",
                        "750"});
            table731.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "750",
                        "750",
                        "750",
                        "750",
                        "750",
                        "0"});
            table731.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
#line 17
 testRunner.And("the following earnings and payments have been made to the provider A for learner " +
                    "a:", ((string)(null)), table731, "And ");
#line hidden
            TechTalk.SpecFlow.Table table732 = new TechTalk.SpecFlow.Table(new string[] {
                        "ULN",
                        "start date",
                        "planned end date",
                        "actual end date",
                        "completion status",
                        "Total training price",
                        "Total training price effective date",
                        "Total assessment price",
                        "Total assessment price effective date"});
            table732.AddRow(new string[] {
                        "learner a",
                        "04/08/2017",
                        "20/08/2018",
                        "12/11/2017",
                        "withdrawn",
                        "9000",
                        "04/08/2017",
                        "2250",
                        "04/08/2017"});
#line 27
    testRunner.When("an ILR file is submitted for the first time on 10/01/18 with the following data:", ((string)(null)), table732, "When ");
#line hidden
            TechTalk.SpecFlow.Table table733 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "12/17",
                        "01/18",
                        "02/18"});
            table733.AddRow(new string[] {
                        "Provider Earned Total",
                        "750",
                        "750",
                        "750",
                        "0",
                        "0",
                        "0",
                        "0"});
            table733.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "750",
                        "750",
                        "750",
                        "0",
                        "0",
                        "0",
                        "0"});
            table733.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table733.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "750",
                        "750",
                        "750",
                        "750",
                        "750",
                        "0"});
            table733.AddRow(new string[] {
                        "Refund taken by SFA",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "-1500"});
            table733.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table733.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "750",
                        "750",
                        "750",
                        "750",
                        "750",
                        "0"});
            table733.AddRow(new string[] {
                        "Levy account credited",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "1500"});
            table733.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "750",
                        "750",
                        "750",
                        "0",
                        "0",
                        "0",
                        "0"});
            table733.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
#line 30
 testRunner.Then("the provider earnings and payments break down as follows:", ((string)(null)), table733, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("673-AC02 Non-DAS learner, levy available, provider retrospectively notifies a wit" +
            "hdrawal and previously-paid monthly instalments need to be refunded.")]
        public virtual void _673_AC02Non_DASLearnerLevyAvailableProviderRetrospectivelyNotifiesAWithdrawalAndPreviously_PaidMonthlyInstalmentsNeedToBeRefunded_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("673-AC02 Non-DAS learner, levy available, provider retrospectively notifies a wit" +
                    "hdrawal and previously-paid monthly instalments need to be refunded.", ((string[])(null)));
#line 44
this.ScenarioSetup(scenarioInfo);
#line 45
 testRunner.Given("the apprenticeship funding band maximum is 17000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table734 = new TechTalk.SpecFlow.Table(new string[] {
                        "ULN",
                        "start date",
                        "aim sequence number",
                        "completion status"});
            table734.AddRow(new string[] {
                        "learner a",
                        "04/08/2017",
                        "1",
                        "continuing"});
#line 46
 testRunner.And("following learning has been recorded for previous payments:", ((string)(null)), table734, "And ");
#line hidden
            TechTalk.SpecFlow.Table table735 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "12/17",
                        "01/18"});
            table735.AddRow(new string[] {
                        "Provider Earned Total",
                        "750",
                        "750",
                        "750",
                        "750",
                        "750",
                        "0"});
            table735.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "675",
                        "675",
                        "675",
                        "675",
                        "675",
                        "0"});
            table735.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "75",
                        "75",
                        "75",
                        "75",
                        "75",
                        "0"});
            table735.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "675",
                        "675",
                        "675",
                        "675",
                        "675"});
            table735.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "75",
                        "75",
                        "75",
                        "75",
                        "75"});
            table735.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table735.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table735.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table735.AddRow(new string[] {
                        "SFA non-Levy co-funding budget",
                        "675",
                        "675",
                        "675",
                        "675",
                        "675",
                        "0"});
#line 50
 testRunner.And("the following earnings and payments have been made to the provider A for learner " +
                    "a:", ((string)(null)), table735, "And ");
#line hidden
            TechTalk.SpecFlow.Table table736 = new TechTalk.SpecFlow.Table(new string[] {
                        "ULN",
                        "learner type",
                        "start date",
                        "planned end date",
                        "actual end date",
                        "completion status",
                        "Total training price",
                        "Total training price effective date",
                        "Total assessment price",
                        "Total assessment price effective date"});
            table736.AddRow(new string[] {
                        "learner a",
                        "programme only non-DAS",
                        "04/08/2017",
                        "20/08/2018",
                        "12/11/2017",
                        "withdrawn",
                        "9000",
                        "04/08/2017",
                        "2250",
                        "04/08/2017"});
#line 61
    testRunner.When("an ILR file is submitted for the first time on 10/01/18 with the following data:", ((string)(null)), table736, "When ");
#line hidden
            TechTalk.SpecFlow.Table table737 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "12/17",
                        "01/18",
                        "02/18"});
            table737.AddRow(new string[] {
                        "Provider Earned Total",
                        "750",
                        "750",
                        "750",
                        "0",
                        "0",
                        "0",
                        "0"});
            table737.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "675",
                        "675",
                        "675",
                        "0",
                        "0",
                        "0",
                        "0"});
            table737.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "75",
                        "75",
                        "75",
                        "0",
                        "0",
                        "0",
                        "0"});
            table737.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "675",
                        "675",
                        "675",
                        "675",
                        "675",
                        "0"});
            table737.AddRow(new string[] {
                        "Refund taken by SFA",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "-1350"});
            table737.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "75",
                        "75",
                        "75",
                        "75",
                        "75",
                        "0"});
            table737.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table737.AddRow(new string[] {
                        "Levy account credited",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table737.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table737.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table737.AddRow(new string[] {
                        "SFA non-Levy co-funding budget",
                        "675",
                        "675",
                        "675",
                        "0",
                        "0",
                        "0",
                        "0"});
#line 64
 testRunner.Then("the provider earnings and payments break down as follows:", ((string)(null)), table737, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("673-AC03 DAS learner, insufficient levy available to cover full payments, provide" +
            "r retrospectively notifies a withdrawal and previously-paid monthly instalments " +
            "need to be refunded.\tGiven The learner is programme only DAS")]
        public virtual void _673_AC03DASLearnerInsufficientLevyAvailableToCoverFullPaymentsProviderRetrospectivelyNotifiesAWithdrawalAndPreviously_PaidMonthlyInstalmentsNeedToBeRefunded_GivenTheLearnerIsProgrammeOnlyDAS()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("673-AC03 DAS learner, insufficient levy available to cover full payments, provide" +
                    "r retrospectively notifies a withdrawal and previously-paid monthly instalments " +
                    "need to be refunded.\tGiven The learner is programme only DAS", ((string[])(null)));
#line 78
this.ScenarioSetup(scenarioInfo);
#line 79
    testRunner.Given("The learner is programme only DAS", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 80
 testRunner.And("the apprenticeship funding band maximum is 17000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 81
    testRunner.And("levy balance > agreed price for all months", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table738 = new TechTalk.SpecFlow.Table(new string[] {
                        "commitment Id",
                        "version Id",
                        "ULN",
                        "start date",
                        "end date",
                        "status",
                        "agreed price",
                        "effective from",
                        "effective to"});
            table738.AddRow(new string[] {
                        "1",
                        "1",
                        "learner a",
                        "01/08/2017",
                        "01/08/2018",
                        "active",
                        "11250",
                        "01/08/2017",
                        ""});
#line 82
 testRunner.And("the following commitments exist:", ((string)(null)), table738, "And ");
#line hidden
            TechTalk.SpecFlow.Table table739 = new TechTalk.SpecFlow.Table(new string[] {
                        "ULN",
                        "start date",
                        "aim sequence number",
                        "completion status"});
            table739.AddRow(new string[] {
                        "learner a",
                        "04/08/2017",
                        "1",
                        "continuing"});
#line 85
 testRunner.And("following learning has been recorded for previous payments:", ((string)(null)), table739, "And ");
#line hidden
            TechTalk.SpecFlow.Table table740 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "12/17",
                        "01/18"});
            table740.AddRow(new string[] {
                        "Provider Earned Total",
                        "750",
                        "750",
                        "750",
                        "750",
                        "750",
                        "0"});
            table740.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "725",
                        "725",
                        "725",
                        "725",
                        "725",
                        "0"});
            table740.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "25",
                        "25",
                        "25",
                        "25",
                        "25",
                        "0"});
            table740.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "725",
                        "725",
                        "725",
                        "725",
                        "725"});
            table740.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "25",
                        "25",
                        "25",
                        "25",
                        "25"});
            table740.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "500",
                        "500",
                        "500",
                        "500",
                        "500"});
            table740.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "500",
                        "500",
                        "500",
                        "500",
                        "500",
                        "0"});
            table740.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "225",
                        "225",
                        "225",
                        "225",
                        "225",
                        "0"});
#line 89
 testRunner.And("the following earnings and payments have been made to the provider A for learner " +
                    "a:", ((string)(null)), table740, "And ");
#line hidden
            TechTalk.SpecFlow.Table table741 = new TechTalk.SpecFlow.Table(new string[] {
                        "ULN",
                        "start date",
                        "planned end date",
                        "actual end date",
                        "completion status",
                        "Total training price",
                        "Total training price effective date",
                        "Total assessment price",
                        "Total assessment price effective date"});
            table741.AddRow(new string[] {
                        "learner a",
                        "04/08/2017",
                        "20/08/2018",
                        "12/11/2017",
                        "withdrawn",
                        "9000",
                        "04/08/2017",
                        "2250",
                        "04/08/2017"});
#line 99
    testRunner.When("an ILR file is submitted for the first time on 10/01/18 with the following data:", ((string)(null)), table741, "When ");
#line hidden
            TechTalk.SpecFlow.Table table742 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "12/17",
                        "01/18",
                        "02/18"});
            table742.AddRow(new string[] {
                        "Provider Earned Total",
                        "750",
                        "750",
                        "750",
                        "0",
                        "0",
                        "0",
                        "0"});
            table742.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "725",
                        "725",
                        "725",
                        "0",
                        "0",
                        "0",
                        "0"});
            table742.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "25",
                        "25",
                        "25",
                        "0",
                        "0",
                        "0",
                        "0"});
            table742.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "725",
                        "725",
                        "725",
                        "725",
                        "725",
                        "0"});
            table742.AddRow(new string[] {
                        "Refund taken by SFA",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "-1450"});
            table742.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "25",
                        "25",
                        "25",
                        "25",
                        "25",
                        "0"});
            table742.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "500",
                        "500",
                        "500",
                        "500",
                        "500",
                        "0"});
            table742.AddRow(new string[] {
                        "Levy account credited",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "1000"});
            table742.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "500",
                        "500",
                        "500",
                        "0",
                        "0",
                        "0",
                        "0"});
            table742.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "225",
                        "225",
                        "225",
                        "0",
                        "0",
                        "0",
                        "0"});
#line 102
 testRunner.Then("the provider earnings and payments break down as follows:", ((string)(null)), table742, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("683-AC01- DAS learner, levy available, 2 providers - provider A and provider B, P" +
            "rovider B retrospectively notifies a withdrawal and previously-paid monthly inst" +
            "alments need to be refunded,")]
        public virtual void _683_AC01_DASLearnerLevyAvailable2Providers_ProviderAAndProviderBProviderBRetrospectivelyNotifiesAWithdrawalAndPreviously_PaidMonthlyInstalmentsNeedToBeRefunded()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("683-AC01- DAS learner, levy available, 2 providers - provider A and provider B, P" +
                    "rovider B retrospectively notifies a withdrawal and previously-paid monthly inst" +
                    "alments need to be refunded,", ((string[])(null)));
#line 116
this.ScenarioSetup(scenarioInfo);
#line 119
 testRunner.Given("The learner is programme only DAS", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 120
 testRunner.And("the apprenticeship funding band maximum is 17000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table743 = new TechTalk.SpecFlow.Table(new string[] {
                        "01/18",
                        "02/18",
                        "03/18",
                        "04/18",
                        "05/18",
                        "06/18",
                        "07/18"});
            table743.AddRow(new string[] {
                        "0",
                        "1125",
                        "1125",
                        "1125",
                        "1125",
                        "1125",
                        "1125"});
#line 121
 testRunner.And("the employer\'s levy balance is:", ((string)(null)), table743, "And ");
#line hidden
            TechTalk.SpecFlow.Table table744 = new TechTalk.SpecFlow.Table(new string[] {
                        "commitment Id",
                        "Provider",
                        "version Id",
                        "ULN",
                        "start date",
                        "end date",
                        "status",
                        "standard code",
                        "agreed price",
                        "effective from",
                        "effective to"});
            table744.AddRow(new string[] {
                        "1",
                        "Provider A",
                        "1",
                        "Learner A",
                        "01/08/2017",
                        "01/08/2018",
                        "active",
                        "25",
                        "5625",
                        "01/08/2017",
                        ""});
            table744.AddRow(new string[] {
                        "2",
                        "Provider B",
                        "1",
                        "Learner B",
                        "01/08/2017",
                        "01/08/2018",
                        "active",
                        "25",
                        "11250",
                        "01/08/2017",
                        ""});
#line 124
 testRunner.And("the following commitments exist:", ((string)(null)), table744, "And ");
#line hidden
            TechTalk.SpecFlow.Table table745 = new TechTalk.SpecFlow.Table(new string[] {
                        "ULN",
                        "start date",
                        "aim sequence number",
                        "completion status",
                        "standard code"});
            table745.AddRow(new string[] {
                        "Learner A",
                        "04/08/2017",
                        "1",
                        "continuing",
                        "25"});
            table745.AddRow(new string[] {
                        "Learner B",
                        "04/08/2017",
                        "1",
                        "continuing",
                        "25"});
#line 129
 testRunner.And("following learning has been recorded for previous payments:", ((string)(null)), table745, "And ");
#line hidden
            TechTalk.SpecFlow.Table table746 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "12/17",
                        "01/18"});
            table746.AddRow(new string[] {
                        "Provider Earned Total",
                        "375",
                        "375",
                        "375",
                        "375",
                        "375",
                        "0"});
            table746.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "375",
                        "375",
                        "375",
                        "375",
                        "375",
                        "0"});
            table746.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table746.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "375",
                        "375",
                        "375",
                        "375",
                        "375"});
            table746.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table746.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "375",
                        "375",
                        "375",
                        "375",
                        "0"});
            table746.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "375",
                        "375",
                        "375",
                        "375",
                        "375",
                        "0"});
            table746.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
#line 135
 testRunner.And("the following earnings and payments have been made to the Provider A for Learner " +
                    "A:", ((string)(null)), table746, "And ");
#line hidden
            TechTalk.SpecFlow.Table table747 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "12/17",
                        "01/18"});
            table747.AddRow(new string[] {
                        "Provider Earned Total",
                        "750",
                        "750",
                        "750",
                        "750",
                        "750",
                        "0"});
            table747.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "750",
                        "750",
                        "750",
                        "750",
                        "750",
                        "0"});
            table747.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table747.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "750",
                        "750",
                        "750",
                        "750",
                        "750"});
            table747.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table747.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "750",
                        "750",
                        "750",
                        "750",
                        "750"});
            table747.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "750",
                        "750",
                        "750",
                        "750",
                        "750",
                        "0"});
            table747.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
#line 145
 testRunner.And("the following earnings and payments have been made to the Provider B for Learner " +
                    "B:", ((string)(null)), table747, "And ");
#line hidden
            TechTalk.SpecFlow.Table table748 = new TechTalk.SpecFlow.Table(new string[] {
                        "ULN",
                        "Provider",
                        "start date",
                        "planned end date",
                        "actual end date",
                        "completion status",
                        "standard code",
                        "Total training price",
                        "Total training price effective date",
                        "Total assessment price",
                        "Total assessment price effective date"});
            table748.AddRow(new string[] {
                        "Learner A",
                        "Provider A",
                        "04/08/2017",
                        "20/08/2018",
                        "",
                        "Continuing",
                        "25",
                        "4500",
                        "04/08/2017",
                        "1125",
                        "04/08/2017"});
            table748.AddRow(new string[] {
                        "Learner B",
                        "Provider B",
                        "04/08/2017",
                        "20/08/2018",
                        "12/11/2017",
                        "withdrawn",
                        "25",
                        "9000",
                        "04/08/2017",
                        "2250",
                        "04/08/2017"});
#line 156
    testRunner.When("an ILR file is submitted for the first time on 10/01/18 with the following data:", ((string)(null)), table748, "When ");
#line hidden
            TechTalk.SpecFlow.Table table749 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "12/17",
                        "01/18",
                        "02/18"});
            table749.AddRow(new string[] {
                        "Provider Earned Total",
                        "375",
                        "375",
                        "375",
                        "375",
                        "375",
                        "375",
                        "375"});
            table749.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "375",
                        "375",
                        "375",
                        "375",
                        "375",
                        "375",
                        "375"});
            table749.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table749.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "375",
                        "375",
                        "375",
                        "375",
                        "375",
                        "375"});
            table749.AddRow(new string[] {
                        "Refund taken by SFA",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table749.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table749.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "375",
                        "375",
                        "375",
                        "375",
                        "375",
                        "375"});
            table749.AddRow(new string[] {
                        "Levy account credited",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table749.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "375",
                        "375",
                        "375",
                        "375",
                        "375",
                        "375",
                        "375"});
            table749.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
#line 161
    testRunner.Then("the earnings and payments break down for provider A is as follows:", ((string)(null)), table749, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table750 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "12/17",
                        "01/18",
                        "02/18"});
            table750.AddRow(new string[] {
                        "Provider Earned Total",
                        "750",
                        "750",
                        "750",
                        "0",
                        "0",
                        "0",
                        "0"});
            table750.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "750",
                        "750",
                        "750",
                        "0",
                        "0",
                        "0",
                        "0"});
            table750.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table750.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "750",
                        "750",
                        "750",
                        "750",
                        "750",
                        "0"});
            table750.AddRow(new string[] {
                        "Refund taken by SFA",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "-1500"});
            table750.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table750.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "750",
                        "750",
                        "750",
                        "750",
                        "750",
                        "0"});
            table750.AddRow(new string[] {
                        "Levy account credited",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "1500"});
            table750.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "750",
                        "750",
                        "750",
                        "0",
                        "0",
                        "0",
                        "0"});
            table750.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
#line 173
    testRunner.Then("the earnings and payments break down for provider B is as follows:", ((string)(null)), table750, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table751 = new TechTalk.SpecFlow.Table(new string[] {
                        "01/18",
                        "02/18",
                        "03/18",
                        "04/18",
                        "05/18",
                        "06/18",
                        "07/18"});
            table751.AddRow(new string[] {
                        "-1125",
                        "750",
                        "750",
                        "750",
                        "750",
                        "750",
                        "750"});
#line 185
  testRunner.And("the net effect on employer\'s levy balance after each period end is:", ((string)(null)), table751, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("780-AC01 - Non-DAS standard learner, price is changed and a negative amount is le" +
            "ft to be paid - results in a refund")]
        public virtual void _780_AC01_Non_DASStandardLearnerPriceIsChangedAndANegativeAmountIsLeftToBePaid_ResultsInARefund()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("780-AC01 - Non-DAS standard learner, price is changed and a negative amount is le" +
                    "ft to be paid - results in a refund", ((string[])(null)));
#line 190
this.ScenarioSetup(scenarioInfo);
#line 191
 testRunner.Given("the apprenticeship funding band maximum is 15000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table752 = new TechTalk.SpecFlow.Table(new string[] {
                        "ULN",
                        "start date",
                        "aim sequence number",
                        "completion status"});
            table752.AddRow(new string[] {
                        "Learner a",
                        "04/08/2017",
                        "1",
                        "continuing"});
#line 193
 testRunner.And("following learning has been recorded for previous payments:", ((string)(null)), table752, "And ");
#line hidden
            TechTalk.SpecFlow.Table table753 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17"});
            table753.AddRow(new string[] {
                        "Provider Earned Total",
                        "750",
                        "750",
                        "0",
                        "0"});
            table753.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "675",
                        "675",
                        "0",
                        "0"});
            table753.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "75",
                        "75",
                        "0",
                        "0"});
            table753.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "675",
                        "675",
                        "0"});
            table753.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "75",
                        "75",
                        "0"});
            table753.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "0",
                        "0",
                        "0"});
            table753.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "0",
                        "0",
                        "0",
                        "0"});
            table753.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0"});
            table753.AddRow(new string[] {
                        "SFA non-Levy co-funding budget",
                        "675",
                        "675",
                        "675",
                        "0"});
#line 196
 testRunner.And("the following earnings and payments have been made to the provider for learner a:" +
                    "", ((string)(null)), table753, "And ");
#line hidden
            TechTalk.SpecFlow.Table table754 = new TechTalk.SpecFlow.Table(new string[] {
                        "ULN",
                        "learner type",
                        "start date",
                        "planned end date",
                        "actual end date",
                        "completion status",
                        "Total training price 1",
                        "Total training price 1 effective date",
                        "Total assessment price 1",
                        "Total assessment price 1 effective date",
                        "Total training price 2",
                        "Total training price 2 effective date",
                        "Total assessment price 2",
                        "Total assessment price 2 effective date"});
            table754.AddRow(new string[] {
                        "learner a",
                        "programme only non-DAS",
                        "04/08/2017",
                        "20/08/2018",
                        "",
                        "continuing",
                        "9000",
                        "04/08/2017",
                        "2250",
                        "04/08/2017",
                        "1200",
                        "04/10/2017",
                        "200",
                        "04/10/2017"});
#line 207
    testRunner.When("an ILR file is submitted on 10/01/18 with the following data:", ((string)(null)), table754, "When ");
#line hidden
            TechTalk.SpecFlow.Table table755 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "12/17",
                        "01/18"});
            table755.AddRow(new string[] {
                        "Provider Earned Total",
                        "750",
                        "750",
                        "-100",
                        "0",
                        "0",
                        "0"});
            table755.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "675",
                        "675",
                        "0",
                        "0",
                        "0",
                        "0"});
            table755.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "75",
                        "75",
                        "0",
                        "0",
                        "0",
                        "0"});
            table755.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "675",
                        "675",
                        "0",
                        "0",
                        "0"});
            table755.AddRow(new string[] {
                        "Refund taken by SFA",
                        "0",
                        "0",
                        "0",
                        "-90",
                        "0",
                        "0"});
            table755.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "75",
                        "75",
                        "0",
                        "0",
                        "0"});
            table755.AddRow(new string[] {
                        "Refund due to employer",
                        "0",
                        "0",
                        "0",
                        "-10",
                        "0",
                        "0"});
            table755.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table755.AddRow(new string[] {
                        "Levy account credited",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table755.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table755.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table755.AddRow(new string[] {
                        "SFA non-Levy co-funding budget",
                        "675",
                        "585",
                        "0",
                        "0",
                        "0",
                        "0"});
#line 210
 testRunner.Then("the provider earnings and payments break down as follows:", ((string)(null)), table755, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("518-AC01 - DAS standard learner, price is changed and a negative amount is left t" +
            "o be paid - results in a refund")]
        [NUnit.Framework.CategoryAttribute("das")]
        public virtual void _518_AC01_DASStandardLearnerPriceIsChangedAndANegativeAmountIsLeftToBePaid_ResultsInARefund()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("518-AC01 - DAS standard learner, price is changed and a negative amount is left t" +
                    "o be paid - results in a refund", new string[] {
                        "das"});
#line 226
this.ScenarioSetup(scenarioInfo);
#line 227
 testRunner.Given("the apprenticeship funding band maximum is 15000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 228
    testRunner.And("levy balance > agreed price for all months", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table756 = new TechTalk.SpecFlow.Table(new string[] {
                        "commitment Id",
                        "version Id",
                        "ULN",
                        "start date",
                        "end date",
                        "status",
                        "agreed price",
                        "effective from",
                        "effective to"});
            table756.AddRow(new string[] {
                        "1",
                        "1",
                        "learner a",
                        "01/08/2017",
                        "01/08/2018",
                        "active",
                        "11250",
                        "01/08/2017",
                        "03/10/2017"});
            table756.AddRow(new string[] {
                        "1",
                        "2",
                        "learner a",
                        "01/08/2017",
                        "01/08/2018",
                        "active",
                        "1400",
                        "04/10/2017",
                        ""});
#line 229
    testRunner.And("the following commitments exist:", ((string)(null)), table756, "And ");
#line hidden
            TechTalk.SpecFlow.Table table757 = new TechTalk.SpecFlow.Table(new string[] {
                        "ULN",
                        "start date",
                        "aim sequence number",
                        "completion status"});
            table757.AddRow(new string[] {
                        "Learner a",
                        "04/08/2017",
                        "1",
                        "continuing"});
#line 234
 testRunner.And("following learning has been recorded for previous payments:", ((string)(null)), table757, "And ");
#line hidden
            TechTalk.SpecFlow.Table table758 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17"});
            table758.AddRow(new string[] {
                        "Provider Earned Total",
                        "750",
                        "750",
                        "0",
                        "0"});
            table758.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "750",
                        "750",
                        "0",
                        "0"});
            table758.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "0",
                        "0",
                        "0",
                        "0"});
            table758.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "750",
                        "750",
                        "0"});
            table758.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "0",
                        "0",
                        "0"});
            table758.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "750",
                        "750",
                        "0"});
            table758.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "0",
                        "0",
                        "0",
                        "0"});
            table758.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0"});
            table758.AddRow(new string[] {
                        "SFA non-Levy co-funding budget",
                        "750",
                        "750",
                        "0",
                        "0"});
#line 237
 testRunner.And("the following earnings and payments have been made to the provider for learner a:" +
                    "", ((string)(null)), table758, "And ");
#line hidden
            TechTalk.SpecFlow.Table table759 = new TechTalk.SpecFlow.Table(new string[] {
                        "ULN",
                        "learner type",
                        "start date",
                        "planned end date",
                        "actual end date",
                        "completion status",
                        "Total training price 1",
                        "Total training price 1 effective date",
                        "Total assessment price 1",
                        "Total assessment price 1 effective date",
                        "Total training price 2",
                        "Total training price 2 effective date",
                        "Total assessment price 2",
                        "Total assessment price 2 effective date"});
            table759.AddRow(new string[] {
                        "learner a",
                        "programme only DAS",
                        "04/08/2017",
                        "20/08/2018",
                        "",
                        "continuing",
                        "9000",
                        "04/08/2017",
                        "2250",
                        "04/08/2017",
                        "1200",
                        "04/10/2017",
                        "200",
                        "04/10/2017"});
#line 249
    testRunner.When("an ILR file is submitted on 10/01/18 with the following data:", ((string)(null)), table759, "When ");
#line hidden
            TechTalk.SpecFlow.Table table760 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "12/17",
                        "01/18"});
            table760.AddRow(new string[] {
                        "Provider Earned Total",
                        "750",
                        "750",
                        "-100",
                        "0",
                        "0",
                        "0"});
            table760.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "750",
                        "750",
                        "0",
                        "0",
                        "0",
                        "0"});
            table760.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table760.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "750",
                        "750",
                        "0",
                        "0",
                        "0"});
            table760.AddRow(new string[] {
                        "Refund taken by SFA",
                        "0",
                        "0",
                        "0",
                        "-100",
                        "0",
                        "0"});
            table760.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table760.AddRow(new string[] {
                        "Refund due to employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table760.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "750",
                        "750",
                        "0",
                        "0",
                        "0"});
            table760.AddRow(new string[] {
                        "Levy account credited",
                        "0",
                        "0",
                        "0",
                        "100",
                        "0",
                        "0"});
            table760.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "750",
                        "650",
                        "0",
                        "0",
                        "0",
                        "0"});
            table760.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table760.AddRow(new string[] {
                        "SFA non-Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
#line 253
    testRunner.Then("the provider earnings and payments break down as follows:", ((string)(null)), table760, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("802-AC01 - DAS standard learner, price is changed, originally mix funded and a ne" +
            "gative amount is left to be paid - results in a refund")]
        [NUnit.Framework.CategoryAttribute("Das")]
        public virtual void _802_AC01_DASStandardLearnerPriceIsChangedOriginallyMixFundedAndANegativeAmountIsLeftToBePaid_ResultsInARefund()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("802-AC01 - DAS standard learner, price is changed, originally mix funded and a ne" +
                    "gative amount is left to be paid - results in a refund", new string[] {
                        "Das"});
#line 269
this.ScenarioSetup(scenarioInfo);
#line 270
 testRunner.Given("the apprenticeship funding band maximum is 15000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table761 = new TechTalk.SpecFlow.Table(new string[] {
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17"});
            table761.AddRow(new string[] {
                        "750",
                        "375",
                        "1000",
                        "1000"});
#line 271
    testRunner.And("the employer\'s levy balance is:", ((string)(null)), table761, "And ");
#line hidden
            TechTalk.SpecFlow.Table table762 = new TechTalk.SpecFlow.Table(new string[] {
                        "commitment Id",
                        "version Id",
                        "ULN",
                        "start date",
                        "end date",
                        "status",
                        "agreed price",
                        "effective from",
                        "effective to"});
            table762.AddRow(new string[] {
                        "1",
                        "1",
                        "learner a",
                        "01/08/2017",
                        "01/08/2018",
                        "active",
                        "11250",
                        "01/08/2017",
                        "03/10/2017"});
            table762.AddRow(new string[] {
                        "1",
                        "2",
                        "learner a",
                        "01/08/2017",
                        "01/08/2018",
                        "active",
                        "1400",
                        "04/10/2017",
                        ""});
#line 274
    testRunner.And("the following commitments exist:", ((string)(null)), table762, "And ");
#line hidden
            TechTalk.SpecFlow.Table table763 = new TechTalk.SpecFlow.Table(new string[] {
                        "ULN",
                        "start date",
                        "aim sequence number",
                        "completion status"});
            table763.AddRow(new string[] {
                        "Learner a",
                        "04/08/2017",
                        "1",
                        "continuing"});
#line 279
 testRunner.And("following learning has been recorded for previous payments:", ((string)(null)), table763, "And ");
#line hidden
            TechTalk.SpecFlow.Table table764 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17"});
            table764.AddRow(new string[] {
                        "Provider Earned Total",
                        "750",
                        "750",
                        "0",
                        "0"});
            table764.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "750",
                        "712.50",
                        "0",
                        "0"});
            table764.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "0",
                        "37.50",
                        "0",
                        "0"});
            table764.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "750",
                        "712.50",
                        "0"});
            table764.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "0",
                        "37.50",
                        "0"});
            table764.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "750",
                        "375",
                        "0"});
            table764.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "750",
                        "375",
                        "0",
                        "0"});
            table764.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "0",
                        "337.50",
                        "0",
                        "0"});
            table764.AddRow(new string[] {
                        "SFA non-Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0"});
#line 283
 testRunner.And("the following earnings and payments have been made to the provider for learner a:" +
                    "", ((string)(null)), table764, "And ");
#line hidden
            TechTalk.SpecFlow.Table table765 = new TechTalk.SpecFlow.Table(new string[] {
                        "ULN",
                        "learner type",
                        "start date",
                        "planned end date",
                        "actual end date",
                        "completion status",
                        "Total training price 1",
                        "Total training price 1 effective date",
                        "Total assessment price 1",
                        "Total assessment price 1 effective date",
                        "Total training price 2",
                        "Total training price 2 effective date",
                        "Total assessment price 2",
                        "Total assessment price 2 effective date"});
            table765.AddRow(new string[] {
                        "learner a",
                        "programme only DAS",
                        "04/08/2017",
                        "20/08/2018",
                        "",
                        "continuing",
                        "9000",
                        "04/08/2017",
                        "2250",
                        "04/08/2017",
                        "1200",
                        "04/10/2017",
                        "200",
                        "04/10/2017"});
#line 295
    testRunner.When("an ILR file is submitted on 10/01/18 with the following data:", ((string)(null)), table765, "When ");
#line hidden
            TechTalk.SpecFlow.Table table766 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "12/17",
                        "01/18"});
            table766.AddRow(new string[] {
                        "Provider Earned Total",
                        "750",
                        "750",
                        "-100",
                        "0",
                        "0",
                        "0"});
            table766.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "750",
                        "712.50",
                        "0",
                        "0",
                        "0",
                        "0"});
            table766.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "0",
                        "37.50",
                        "0",
                        "0",
                        "0",
                        "0"});
            table766.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "750",
                        "712.50",
                        "0",
                        "0",
                        "0"});
            table766.AddRow(new string[] {
                        "Refund taken by SFA",
                        "0",
                        "0",
                        "0",
                        "-95",
                        "0",
                        "0"});
            table766.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "0",
                        "37.50",
                        "0",
                        "0",
                        "0"});
            table766.AddRow(new string[] {
                        "Refund due to employer",
                        "0",
                        "0",
                        "0",
                        "5",
                        "0",
                        "0"});
            table766.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "750",
                        "375",
                        "0",
                        "0",
                        "0"});
            table766.AddRow(new string[] {
                        "Levy account credited",
                        "0",
                        "0",
                        "0",
                        "50",
                        "0",
                        "0"});
            table766.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "750",
                        "325",
                        "0",
                        "0",
                        "0",
                        "0"});
            table766.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "0",
                        "292.50",
                        "0",
                        "0",
                        "0",
                        "0"});
            table766.AddRow(new string[] {
                        "SFA non-Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
#line 299
    testRunner.Then("the provider earnings and payments break down as follows:", ((string)(null)), table766, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
