// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SFA.DAS.Payments.AcceptanceTests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("2 learners, paid in priority order")]
    [NUnit.Framework.CategoryAttribute("LearnersPaidInPriority")]
    public partial class _2LearnersPaidInPriorityOrderFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "two_learners_paid_in_priority.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-GB"), "2 learners, paid in priority order", null, ProgrammingLanguage.CSharp, new string[] {
                        "LearnersPaidInPriority"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 4
    #line 5
        testRunner.Given("Two learners are programme only DAS", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 6
        testRunner.And("the apprenticeship funding band maximum for each learner is 17000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Earnings and payments for two DAS learners, levy is spent in priority order and a" +
            "vailable for both learners")]
        public virtual void EarningsAndPaymentsForTwoDASLearnersLevyIsSpentInPriorityOrderAndAvailableForBothLearners()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Earnings and payments for two DAS learners, levy is spent in priority order and a" +
                    "vailable for both learners", ((string[])(null)));
#line 8
    this.ScenarioSetup(scenarioInfo);
#line 4
    this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table844 = new TechTalk.SpecFlow.Table(new string[] {
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "...",
                        "08/18",
                        "09/18"});
            table844.AddRow(new string[] {
                        "2000",
                        "2000",
                        "2000",
                        "2000",
                        "2000",
                        "2000",
                        "2000"});
#line 9
        testRunner.Given("the employer\'s levy balance is:", ((string)(null)), table844, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table845 = new TechTalk.SpecFlow.Table(new string[] {
                        "priority",
                        "ULN",
                        "start date",
                        "end date",
                        "agreed price"});
            table845.AddRow(new string[] {
                        "1",
                        "123",
                        "01/08/2017",
                        "28/08/2018",
                        "15000"});
            table845.AddRow(new string[] {
                        "2",
                        "456",
                        "01/08/2017",
                        "28/08/2018",
                        "15000"});
#line 12
        testRunner.And("the following commitments exist on 03/12/2017:", ((string)(null)), table845, "And ");
#line hidden
            TechTalk.SpecFlow.Table table846 = new TechTalk.SpecFlow.Table(new string[] {
                        "ULN",
                        "start date",
                        "planned end date",
                        "actual end date",
                        "completion status",
                        "Total training price",
                        "Total training price effective date",
                        "Total assessment price",
                        "Total assessment price effective date"});
            table846.AddRow(new string[] {
                        "123",
                        "01/08/2017",
                        "28/08/2018",
                        "",
                        "continuing",
                        "12000",
                        "01/08/2017",
                        "3000",
                        "01/08/2017"});
            table846.AddRow(new string[] {
                        "456",
                        "01/08/2017",
                        "28/08/2018",
                        "",
                        "continuing",
                        "12000",
                        "01/08/2017",
                        "3000",
                        "01/08/2017"});
#line 16
        testRunner.When("an ILR file is submitted on 03/12/2017 with the following data:", ((string)(null)), table846, "When ");
#line hidden
            TechTalk.SpecFlow.Table table847 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "...",
                        "07/18",
                        "08/18"});
            table847.AddRow(new string[] {
                        "Provider Earned Total",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0"});
            table847.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0"});
            table847.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table847.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "1000"});
            table847.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table847.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "1000"});
            table847.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0"});
            table847.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table847.AddRow(new string[] {
                        "SFA non-Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
#line 20
        testRunner.Then("the provider earnings and payments break down for ULN 123 as follows:", ((string)(null)), table847, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table848 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "...",
                        "07/18",
                        "08/18"});
            table848.AddRow(new string[] {
                        "Provider Earned Total",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0"});
            table848.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0"});
            table848.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table848.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "1000"});
            table848.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table848.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "1000"});
            table848.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0"});
            table848.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table848.AddRow(new string[] {
                        "SFA non-Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
#line 31
        testRunner.And("the provider earnings and payments break down for ULN 456 as follows:", ((string)(null)), table848, "And ");
#line hidden
            TechTalk.SpecFlow.Table table849 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "...",
                        "07/18",
                        "08/18"});
            table849.AddRow(new string[] {
                        "Provider Earned Total",
                        "2000",
                        "2000",
                        "2000",
                        "2000",
                        "...",
                        "2000",
                        "0"});
            table849.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "2000",
                        "2000",
                        "2000",
                        "2000",
                        "...",
                        "2000",
                        "0"});
            table849.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table849.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "2000",
                        "2000",
                        "2000",
                        "...",
                        "2000",
                        "2000"});
            table849.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table849.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "2000",
                        "2000",
                        "2000",
                        "...",
                        "2000",
                        "2000"});
            table849.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "2000",
                        "2000",
                        "2000",
                        "2000",
                        "...",
                        "2000",
                        "0"});
            table849.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table849.AddRow(new string[] {
                        "SFA non-Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
#line 42
        testRunner.And("the provider earnings and payments break down as follows:", ((string)(null)), table849, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Earnings and payments for two DAS learners, levy is spent in priority order and i" +
            "s available for one learner only")]
        public virtual void EarningsAndPaymentsForTwoDASLearnersLevyIsSpentInPriorityOrderAndIsAvailableForOneLearnerOnly()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Earnings and payments for two DAS learners, levy is spent in priority order and i" +
                    "s available for one learner only", ((string[])(null)));
#line 55
    this.ScenarioSetup(scenarioInfo);
#line 4
    this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table850 = new TechTalk.SpecFlow.Table(new string[] {
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "...",
                        "08/18",
                        "09/18"});
            table850.AddRow(new string[] {
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "1000"});
#line 56
        testRunner.Given("the employer\'s levy balance is:", ((string)(null)), table850, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table851 = new TechTalk.SpecFlow.Table(new string[] {
                        "priority",
                        "ULN",
                        "start date",
                        "end date",
                        "agreed price"});
            table851.AddRow(new string[] {
                        "1",
                        "123",
                        "01/08/2017",
                        "28/08/2018",
                        "15000"});
            table851.AddRow(new string[] {
                        "2",
                        "456",
                        "01/08/2017",
                        "28/08/2018",
                        "15000"});
#line 59
        testRunner.And("the following commitments exist on 03/12/2017:", ((string)(null)), table851, "And ");
#line hidden
            TechTalk.SpecFlow.Table table852 = new TechTalk.SpecFlow.Table(new string[] {
                        "ULN",
                        "start date",
                        "planned end date",
                        "actual end date",
                        "completion status",
                        "Total training price",
                        "Total training price effective date",
                        "Total assessment price",
                        "Total assessment price effective date"});
            table852.AddRow(new string[] {
                        "123",
                        "01/08/2017",
                        "28/08/2018",
                        "",
                        "continuing",
                        "12000",
                        "01/08/2017",
                        "3000",
                        "01/08/2017"});
            table852.AddRow(new string[] {
                        "456",
                        "01/08/2017",
                        "28/08/2018",
                        "",
                        "continuing",
                        "12000",
                        "01/08/2017",
                        "3000",
                        "01/08/2017"});
#line 63
        testRunner.When("an ILR file is submitted on 03/12/2017 with the following data:", ((string)(null)), table852, "When ");
#line hidden
            TechTalk.SpecFlow.Table table853 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "...",
                        "07/18",
                        "08/18"});
            table853.AddRow(new string[] {
                        "Provider Earned Total",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0"});
            table853.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0"});
            table853.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table853.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "1000"});
            table853.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table853.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "1000"});
            table853.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0"});
            table853.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table853.AddRow(new string[] {
                        "SFA non-Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
#line 67
        testRunner.Then("the provider earnings and payments break down for ULN 123 as follows:", ((string)(null)), table853, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table854 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "...",
                        "07/18",
                        "08/18"});
            table854.AddRow(new string[] {
                        "Provider Earned Total",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0"});
            table854.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "900",
                        "900",
                        "900",
                        "900",
                        "...",
                        "900",
                        "0"});
            table854.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "100",
                        "100",
                        "100",
                        "100",
                        "...",
                        "100",
                        "0"});
            table854.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "900",
                        "900",
                        "900",
                        "...",
                        "900",
                        "900"});
            table854.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "100",
                        "100",
                        "100",
                        "...",
                        "100",
                        "100"});
            table854.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table854.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table854.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "900",
                        "900",
                        "900",
                        "900",
                        "...",
                        "900",
                        "0"});
            table854.AddRow(new string[] {
                        "SFA non-Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
#line 78
        testRunner.And("the provider earnings and payments break down for ULN 456 as follows:", ((string)(null)), table854, "And ");
#line hidden
            TechTalk.SpecFlow.Table table855 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "...",
                        "07/18",
                        "08/18"});
            table855.AddRow(new string[] {
                        "Provider Earned Total",
                        "2000",
                        "2000",
                        "2000",
                        "2000",
                        "...",
                        "2000",
                        "0"});
            table855.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "1900",
                        "1900",
                        "1900",
                        "1900",
                        "...",
                        "1900",
                        "0"});
            table855.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "100",
                        "100",
                        "100",
                        "100",
                        "...",
                        "100",
                        "0"});
            table855.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "1900",
                        "1900",
                        "1900",
                        "...",
                        "1900",
                        "1900"});
            table855.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "100",
                        "100",
                        "100",
                        "...",
                        "100",
                        "100"});
            table855.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "1000"});
            table855.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0"});
            table855.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "900",
                        "900",
                        "900",
                        "900",
                        "...",
                        "900",
                        "0"});
            table855.AddRow(new string[] {
                        "SFA non-Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
#line 89
        testRunner.And("the provider earnings and payments break down as follows:", ((string)(null)), table855, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Earnings and payments for two DAS learners, levy is spent in priority order and t" +
            "here is enough levy to fund one and a half learners")]
        public virtual void EarningsAndPaymentsForTwoDASLearnersLevyIsSpentInPriorityOrderAndThereIsEnoughLevyToFundOneAndAHalfLearners()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Earnings and payments for two DAS learners, levy is spent in priority order and t" +
                    "here is enough levy to fund one and a half learners", ((string[])(null)));
#line 102
    this.ScenarioSetup(scenarioInfo);
#line 4
    this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table856 = new TechTalk.SpecFlow.Table(new string[] {
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "...",
                        "08/18",
                        "09/18"});
            table856.AddRow(new string[] {
                        "1500",
                        "1500",
                        "1500",
                        "1500",
                        "1500",
                        "1500",
                        "1500"});
#line 103
        testRunner.Given("the employer\'s levy balance is:", ((string)(null)), table856, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table857 = new TechTalk.SpecFlow.Table(new string[] {
                        "priority",
                        "ULN",
                        "start date",
                        "end date",
                        "agreed price"});
            table857.AddRow(new string[] {
                        "1",
                        "123",
                        "01/08/2017",
                        "28/08/2018",
                        "15000"});
            table857.AddRow(new string[] {
                        "2",
                        "456",
                        "01/08/2017",
                        "28/08/2018",
                        "15000"});
#line 106
        testRunner.And("the following commitments exist on 03/12/2017:", ((string)(null)), table857, "And ");
#line hidden
            TechTalk.SpecFlow.Table table858 = new TechTalk.SpecFlow.Table(new string[] {
                        "ULN",
                        "start date",
                        "planned end date",
                        "actual end date",
                        "completion status",
                        "Total training price",
                        "Total training price effective date",
                        "Total assessment price",
                        "Total assessment price effective date"});
            table858.AddRow(new string[] {
                        "123",
                        "01/08/2017",
                        "28/08/2018",
                        "",
                        "continuing",
                        "12000",
                        "01/08/2017",
                        "3000",
                        "01/08/2017"});
            table858.AddRow(new string[] {
                        "456",
                        "01/08/2017",
                        "28/08/2018",
                        "",
                        "continuing",
                        "12000",
                        "01/08/2017",
                        "3000",
                        "01/08/2017"});
#line 110
        testRunner.When("an ILR file is submitted on 03/12/2017 with the following data:", ((string)(null)), table858, "When ");
#line hidden
            TechTalk.SpecFlow.Table table859 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "...",
                        "07/18",
                        "08/18"});
            table859.AddRow(new string[] {
                        "Provider Earned Total",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0"});
            table859.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0"});
            table859.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table859.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "1000"});
            table859.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table859.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "1000"});
            table859.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0"});
            table859.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
            table859.AddRow(new string[] {
                        "SFA non-Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
#line 114
        testRunner.Then("the provider earnings and payments break down for ULN 123 as follows:", ((string)(null)), table859, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table860 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "...",
                        "07/18",
                        "08/18"});
            table860.AddRow(new string[] {
                        "Provider Earned Total",
                        "1000",
                        "1000",
                        "1000",
                        "1000",
                        "...",
                        "1000",
                        "0"});
            table860.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "950",
                        "950",
                        "950",
                        "950",
                        "...",
                        "950",
                        "0"});
            table860.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "50",
                        "50",
                        "50",
                        "50",
                        "...",
                        "50",
                        "0"});
            table860.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "950",
                        "950",
                        "950",
                        "...",
                        "950",
                        "950"});
            table860.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "50",
                        "50",
                        "50",
                        "...",
                        "50",
                        "50"});
            table860.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "500",
                        "500",
                        "500",
                        "...",
                        "500",
                        "500"});
            table860.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "500",
                        "500",
                        "500",
                        "500",
                        "...",
                        "500",
                        "0"});
            table860.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "450",
                        "450",
                        "450",
                        "450",
                        "...",
                        "450",
                        "0"});
            table860.AddRow(new string[] {
                        "SFA non-Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
#line 125
        testRunner.And("the provider earnings and payments break down for ULN 456 as follows:", ((string)(null)), table860, "And ");
#line hidden
            TechTalk.SpecFlow.Table table861 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "08/17",
                        "09/17",
                        "10/17",
                        "11/17",
                        "...",
                        "07/18",
                        "08/18"});
            table861.AddRow(new string[] {
                        "Provider Earned Total",
                        "2000",
                        "2000",
                        "2000",
                        "2000",
                        "...",
                        "2000",
                        "0"});
            table861.AddRow(new string[] {
                        "Provider Earned from SFA",
                        "1950",
                        "1950",
                        "1950",
                        "1950",
                        "...",
                        "1950",
                        "0"});
            table861.AddRow(new string[] {
                        "Provider Earned from Employer",
                        "50",
                        "50",
                        "50",
                        "50",
                        "...",
                        "50",
                        "0"});
            table861.AddRow(new string[] {
                        "Provider Paid by SFA",
                        "0",
                        "1950",
                        "1950",
                        "1950",
                        "...",
                        "1950",
                        "1950"});
            table861.AddRow(new string[] {
                        "Payment due from Employer",
                        "0",
                        "50",
                        "50",
                        "50",
                        "...",
                        "50",
                        "50"});
            table861.AddRow(new string[] {
                        "Levy account debited",
                        "0",
                        "1500",
                        "1500",
                        "1500",
                        "...",
                        "1500",
                        "1500"});
            table861.AddRow(new string[] {
                        "SFA Levy employer budget",
                        "1500",
                        "1500",
                        "1500",
                        "1500",
                        "...",
                        "1500",
                        "0"});
            table861.AddRow(new string[] {
                        "SFA Levy co-funding budget",
                        "450",
                        "450",
                        "450",
                        "450",
                        "...",
                        "450",
                        "0"});
            table861.AddRow(new string[] {
                        "SFA non-Levy co-funding budget",
                        "0",
                        "0",
                        "0",
                        "0",
                        "...",
                        "0",
                        "0"});
#line 136
        testRunner.And("the provider earnings and payments break down as follows:", ((string)(null)), table861, "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
